//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Snipe.rc
//
#define IDR_MANIFEST                    1
#define IDS_TITLE_SELECTIONTOOLBAR      2
#define IDR_MAINFRAME                   128
#define IDS_TITLE_STANDARDBAR           129
#define IDS_TITLE_FULLSCREENBAR         130
#define IDS_STATUSBAR                   131
#define IDS_VISIBLE                     132
#define IDS_WINDOWMENU                  133
#define ID_VIEW_MENUBAR                 134
#define ID_EDIT_DELETE                  135
#define ID_VIEW_STANDARDBAR             136
#define ID_VIEW_FULLSCREENBAR           137
#define ID_OUTPUTCONTROL                138
#define IDR_OBJECTPROPERTIES            139
#define IDD_ABOUTBOX                    140
#define IDR_VIEWPROPERTIES              140
#define ID_SPLITTER_WINDOWLIST          141
#define IDR_NEWBUTTON_MENU              142
#define ID_SPLITTER_CLOSE               143
#define IDR_BASEDOCFRAME                144
#define IDB_TREEICONS                   145
#define IDB_TREEEXPAND                  146
#define IDB_NUMERICALEDIT               147
#define ID_VIEW_FULLSCREEN              148
#define IDB_BACKGROUND                  149
#define IDB_BUTTON                      150
#define IDB_SLIDERKNOB                  151
#define IDB_SLIDERBAR                   152
#define IDB_PROPERTYEXPAND              153
#define IDB_COLORCHIP                   154
#define IDR_OBJ_IMAGE                   155
#define IDR_HISTORYCONTROL              156
#define IDR_CAMERALOGO_GEO              157
#define IDR_SPLITTER                    158
#define IDR_MODELVIEW                   159
#define IDR_SNIPETYPE                   160
#define IDR_MODELTYPE                   161
#define IDR_IMAGETYPE                   162
#define IDR_IMAGEVIEW                   163
#define IDR_OBJ_POLYMODEL               164
#define IDB_GROUPBOX                    165
#define IDR_TABCONTROL                  166
#define IDR_DOCUMENTTABCONTROL          167
#define IDB_VSCROLL                     168
#define IDB_SCROLLKNOBV                 169
#define IDR_OUTPUTCONTROL               170
#define IDB_TOOLBARBUTTON               171
#define IDR_SCENETYPE                   172
#define IDB_SPLITTERKNOB                173
#define IDB_TABS                        175
#define IDR_TEXCOORDVIEW                176
#define IDB_TABBORDER                   177
#define IDR_OUTPUTCONTROL1              177
#define IDR_POINTERPROPERTYCONTROL      177
#define IDB_TABSTOP                     178
#define IDR_MOTIONVIEW                  178
#define IDB_COMBOBOX                    179
#define IDR_MOTIONTYPE                  179
#define IDB_PROGRESSCONTROL             180
#define IDR_MODELVIEW2                  180
#define IDR_MOTIONSETVIEW               180
#define IDB_HISTORYICONS                181
#define IDR_MOTIONSETTYPE               181
#define ID_VIEW_MODELEXPLORER           182
#define ID_VIEW_IMAGEEXPLORER           183
#define ID_VIEW_PROJECTEXPLORER         184
#define IDB_TITLEBAR                    185
#define ID_VIEW_TOOLBOX                 186
#define IDB_TITLEBARBUTTON              187
#define ID_VIEW_SCENEEXPLORER           188
#define IDB_TABBORDER2                  189
#define ID_VIEW_PROPERTYBAR             190
#define IDB_TABSTOPBORDER               191
#define ID_VIEW_ANGLEPRESET_COMBO2      191
#define ID_VIEW_MODE_COMBO              191
#define ID_VIEW_ANGLEPRESET_COMBO       192
#define IDD_COMMANDS                    193
#define IDS_TITLE_PROJECTEXPLORER       194
#define IDD_TOOLBARS                    195
#define IDS_TITLE_SCENEEXPLORER         196
#define IDD_STRING                      197
#define IDS_TITLE_MODELEXPLORER         198
#define IDB_EDITBOX                     199
#define IDS_TITLE_IMAGEEXPLORER         200
#define IDR_CAMERA_GEO                  201
#define ID_VIEW_OUTPUTBAR               202
#define IDR_LIGHT_GEO                   203
#define IDS_TITLE_OUTPUTBAR             204
#define IDS_TITLE_PROPERTYBAR           205
#define IDS_ALLOWDOCKING                206
#define ID_OUTPUT_CLEAR                 207
#define ID_DOCUMENT_TAB                 208
#define IDR_COMPONENTTYPE_COMBO         209
#define IDR_MANIPULATOR_COMBO           210
#define ID_TEXCOORD_COMBO               211
#define ID_TEXCOORDINSTANCE_COMBO       212
#define ID_BROWSEEDIT                   213
#define IDS_NOTSET                      214
#define IDR_SPHERE_GEO                  215
#define IDR_MANIPULATORPROPERTIES       216
#define IDR_NAVIGATORPROPERTIES         217
#define IDB_BITMAP2                     218
#define IDC_GROUP_LIST                  221
#define ID_DISPLAYAS_PATCHMODEL         222
#define IDC_COMMAND_LIST                223
#define ID_DISPLAYAS_POLYMODEL          224
#define IDC_SHORTCUTSFORCOMMAND_LIST    225
#define IDB_BITMAP1                     226
#define IDB_FONT                        227
#define IDC_HOTKEY                      228
#define IDB_BITMAP3                     229
#define IDB_SPLASH                      230
#define IDC_ASSIGN_BUTTON               231
#define IDC_SHORTCUTUSEDFOR_LIST        232
#define IDS_MODELFILTER                 233
#define IDC_TOOLBAR_LIST                234
#define IDS_PROJECTFILTER               235
#define IDC_NEW_BUTTON                  236
#define IDS_SCENEFILTER                 237
#define IDC_RENAME_BUTTON               238
#define IDS_ALLFORMATS                  239
#define IDC_DELETE_BUTTON               240
#define ID_MIRROR_MODE                  241
#define IDC_RESET_BUTTON                242
#define IDC_REQUEST_STATIC              243
#define IDC_STRING_EDIT                 244
#define IDB_TARGET                      245
#define IDB_BITMAP4                     246
#define IDB_STATUSPANE                  246
#define IDB_BITMAP5                     247
#define IDB_MOUSE                       247
#define IDR_GEOMETRY1                   248
#define IDR_BONE_GEO                    248
#define ID_DISPLAY_SHADED               250
#define ID_DISPLAY_WIREFRAME            251
#define ID_DISPLAY_SHADEDWIREFRAME      252
#define ID_DISPLAY_CONTROLPOINTS        253
#define ID_DISPLAY_GRID                 254
#define ID_DISPLAY_TEXTURES             255
#define ID_DISPLAY_SUBDIVISIONS         256
#define ID_DISPLAY_RULERS               257
#define IDB_RESTORE                     258
#define ID_RESTORE                      258
#define IDB_MAXIMIZE                    259
#define ID_MAXIMIZE                     259
#define IDB_ALLMODIFIERS                260
#define IDB_BITMAP6                     261
#define IDB_PLAY                        261
#define IDB_BITMAP7                     262
#define IDB_TRANSPORTBUTTON             262
#define IDB_BITMAP8                     263
#define IDB_BITMAP9                     264
#define IDB_BITMAP10                    265
#define IDB_BITMAP11                    266
#define IDB_BITMAP12                    267
#define IDB_BITMAP13                    268
#define IDB_BITMAP14                    269
#define IDB_BITMAP15                    270
#define ID_PLAYMUTE                     270
#define IDB_BITMAP16                    271
#define ID_PLAYBUTTON                   271
#define IDB_PLAYBUTTON                  271
#define IDB_BITMAP17                    272
#define IDB_KEY                         272
#define IDR_MENU1                       274
#define IDS_SOT_Unknown                 1000
#define IDS_SOT_Poly                    1006
#define IDS_SOT_Edge                    1007
#define IDS_SOT_Patch                   1009
#define IDS_SOT_Vertex                  1010
#define IDS_SOT_UV                      1016
#define IDS_SOT_BezierSpline            1031
#define IDS_SOT_TransformableObject     1051
#define IDS_SOT_Bone                    1055
#define ID_RECORD                       1056
#define ID_GOTOSTART                    1057
#define ID_GOTOEND                      1058
#define ID_PLAYFROMSTART                1059
#define ID_PLAY                         1060
#define ID_PAUSE                        1061
#define ID_LOOPPLAYBACK                 1062
#define ID_GOTOPREVIOUSFRAME            1063
#define ID_GOTONEXTFRAME                1064
#define ID_PLAYMUTEAUDIO                1065
#define ID_CURRENTFRAMEEDIT             1066
#define ID_STARTFRAMEEDIT               1067
#define ID_ENDFRAMEEDIT                 1068
#define IDS_SOT_Key                     1085
#define IDS_SOT_MotionChannelBiasObject 1109
#define ID_TAB_ITEM_FIRST               9000
#define ID_TAB_ITEM_LAST                9499
#define ID_TABCONTROL_LAYOUT_FIRST      9500
#define ID_TABCONTROL_LAYOUT_LAST       9999
#define ID_PLUGIN_COMMAND_FIRST         10000
#define ID_PLUGIN_COMMAND_LAST          20000
#define ID_FILE_NEW_PROJECT             32772
#define ID_FILE_OPEN_PROJECT            32773
#define ID_FILE_SAVE_ALL                32774
#define ID_VIEW_FRONT                   32781
#define ID_VIEW_BACK                    32782
#define ID_VIEW_LEFT                    32783
#define ID_VIEW_RIGHT                   32784
#define ID_VIEW_TOP                     32785
#define ID_VIEW_BOTTOM                  32786
#define ID_VIEW_BIRDSEYE                32787
#define ID_VIEW_CAMERA                  32789
#define ID_VIEW_LIGHT                   32790
#define IDS_VIEW_LIGHT                  32790
#define ID_FILE_NEW_MODEL               32791
#define ID_FILE_NEW_SCENE               32792
#define ID_FILE_OPEN_MODEL              32793
#define ID_FILE_OPEN_SCENE              32795
#define ID_FILE_CLOSEPROJECT            32798
#define ID_SPLITTER_ADDHORIZONTALSPLIT  32801
#define ID_SPLITTER_ADDVERTICALSPLIT    32802
#define ID_SPLITTER_REMOVEHORIZONTALSPLIT 32803
#define ID_SPLITTER_REMOVEVERTICALSPLIT 32804
#define ID_SPLIT_HORIZONTALLY           32806
#define ID_SPLIT_VERTICALLY             32807
#define ID_SPLIT_BOTH                   32808
#define ID_TOOLS_CUSTOMIZE              32814
#define ID_WINDOW_CLOSEALLDOCUMENTS     32818
#define ID_FILE_NEW_MODEL_POLYGONAL     32830
#define ID_FILE_NEW_MODEL_PATCH         32831
#define ID_FILE_NEW_ACTION              32834
#define ID_FILE_SAVEPROJECT             32845
#define ID_FILE_SAVEPROJECTAS           32846
#define ID_VIEW_SELECTMODE_VERTEX       32850
#define ID_VIEW_SELECTMODE_FACE         32852
#define ID_VIEW_SELECTMODE_EDGE         32853
#define ID_VIEW_SELECTMODE_SPLINE       32854
#define ID_VIEW_SELECTMODE_OBJECT       32856
#define ID_VIEW_SELECTMODE_BONE         32857
#define ID_VIEW_ZOOMFITALL              32867
#define ID_OBJECT_EDIT                  32868
#define ID_TABCONTROL_CLOSE             32872
#define ID_TABCONTROL_CLOSEALLBUTTHIS   32873
#define ID_TABCONTROL_NEWHORIZONTALTABGROUP 32874
#define ID_TABCONTROL_NEWVERTICALTABGROUP 32875
#define ID_TABCONTROL_MOVETONEXTTABGROUP 32876
#define ID_TABCONTROL_MOVETOPREVIOUSTABGROUP 32877
#define ID_EXPORT_MODEL                 32884
#define ID_EXPORT_IMAGE                 32885
#define ID_IMPORT_MODEL                 32886
#define ID_IMPORT_IMAGE                 32887
#define ID_VIEW_ZOOMFITSELECTED         32888
#define ID_ACCELERATOR32890             32890
#define ID_ACCELERATOR32892             32892
#define ID_TABCONTROL_LAYOUT_NEW        32896
#define ID_VIEW_TOGGLEMAXIMIZE          32898
#define ID_TOGGLE_PERSPECTIVE           32900
#define ID_IMPORT_SCENE                 32905
#define ID_EXPORT_SCENE                 32906
#define ID_POINTERPROPERTY_SELECTOBJECT 32911
#define ID_IMPORT_MOTION                32912
#define ID_PREVFRAME                    32914
#define ID_EXPORT_MOTION                32916
#define ID_COMMANDLINE                  32917
#define ID_FILE_NEW_MOTIONSET           32920
#define ID_EXPORT_MOTIONSET             32922
#define ID_IMPORT_MOTIONSET             32923
#define ID_CLOSE                        57000
#define ID_NEW                          57001
#define ID_RENAME                       57002
#define ID_DELETE                       57003
#define ID_RESET                        57004
#define ID_VIEW_MENU                    59394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        275
#define _APS_NEXT_COMMAND_VALUE         32924
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
