//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BasicCommandsPlugin.rc
//
#define IDC_TOGGLE                      2
#define IDB_SELECT                      1002
#define IDB_POLYLASSOSELECT             1005
#define IDB_BOUNDSELECT                 1006
#define IDB_LASSOSELECT                 1007
#define IDC_SELECTION_COMBO             1007
#define IDC_NAME_EDIT                   1008
#define IDC_NOADD_ALONGEDGE             1008
#define IDC_NEW_RADIO                   1009
#define IDC_ADD_RADIO                   1010
#define IDC_SUBTRACT_RADIO              1011
#define IDC_ADD                         1011
#define IDC_TOGGLE_RADIO                1012
#define IDC_ADD_ALONGEDGE               1012
#define IDC_NAME_STATIC                 1013
#define IDC_CANTADD_ALONGEDGE           1013
#define IDB_DELETE                      1014
#define IDC_SURFACE_COMBO               1014
#define IDB_DESELECTALL                 1015
#define IDC_TOMODELTYPE                 1015
#define IDC_TOMODELTYPE_COMBO           1015
#define IDB_SELECTALL                   1016
#define IDC_CONVERTTOSTATIC             1016
#define IDB_HIDE                        1017
#define IDC_TOLERANCE_EDIT              1017
#define IDB_SPLITPOLY                   1018
#define IDB_SHOWSELECTION               1020
#define IDC_TOLERANCE_SPIN              1020
#define IDB_HIDESELECTION               1021
#define IDC_TOLERANCE_STATIC            1021
#define IDB_SHOWALL                     1022
#define IDB_SELECTINVERSE               1023
#define IDR_TRANSLATEMANIPULATORZ_GEO   1026
#define IDR_SCALEMANIPULATORKNOB_GEO    1027
#define IDR_ROTATEMANIPULATORALL_GEO    1030
#define IDR_ROTATEMANIPULATORSCREEN_GEO 1031
#define IDR_ROTATEMANIPULATORZ_GEO      1034
#define IDB_ROTATE                      1035
#define IDB_TRANSLATE                   1036
#define IDB_SCALE                       1037
#define IDB_SINGLESELECT                1038
#define IDB_PAINTSELECT                 1039
#define IDB_SUBDIVIDEUP                 1041
#define IDB_SUBDIVIDEDOWN               1042
#define IDB_STOREVALUE                  1045
#define IDD_SAVESELECTION_DIALOG        1046
#define IDD_CREATESURFACE_DIALOG        1047
#define IDB_SELECTCONTINUOUS            1048
#define IDB_SELECTCONNECTED             1049
#define IDB_ROTATEFOCUSPREV             1050
#define IDB_ROTATEFOCUSNEXT             1051
#define IDB_CONSTRAINVERTEX             1053
#define IDB_SHRINKSELECTION             1054
#define IDB_GROWSELECTION               1055
#define IDB_VERTEX                      1056
#define IDB_EDGE                        1057
#define IDB_FACE                        1058
#define IDB_BITMAP1                     1061
#define IDB_REDIRECT                    1061
#define IDR_PIVOTMANIPULATOR_GEO        1064
#define IDR_PIVOTMANIPULATORROTATE_GEO  1064
#define IDC_CURSOR1                     1065
#define IDC_LASSO                       1065
#define IDC_POLYLASSO                   1066
#define IDC_LASSO_ADD                   1067
#define IDB_BITMAP2                     1067
#define IDB_WELD                        1067
#define IDB_COLLAPSE                    1067
#define IDC_LASSO_SUBTRACT              1068
#define IDB_BITMAP3                     1068
#define IDB_ADDVERTEX                   1068
#define IDC_LASSO_TOGGLE                1069
#define IDB_BITMAP4                     1069
#define IDB_ATTACH                      1069
#define IDC_SUBTRACT                    1070
#define IDB_BITMAP5                     1070
#define IDB_CONVERT                     1070
#define IDD_CONVERTMODEL_DIALOG         1071
#define IDB_DEFAULT                     1071
#define IDC_POLYLASSO_ADD               1072
#define IDD_COMPRESSMOTION_DIALOG       1072
#define IDD_REDUCEMOTIONKEYS_DIALOG     1072
#define IDC_POLYLASSO_SUBTRACT          1073
#define IDB_BITMAP6                     1073
#define IDB_TERMINATE                   1073
#define IDC_POLYLASSO_TOGGLE            1074
#define IDB_BITMAP7                     1074
#define IDB_CREATEFACE                  1074
#define IDC_SINGLEPICK                  1075
#define IDB_BITMAP8                     1075
#define IDB_DELETEFACE                  1075
#define IDC_BOUND                       1076
#define IDB_BITMAP9                     1076
#define IDB_FLIPNORMAL                  1076
#define IDC_BOUND_ADD                   1077
#define IDB_ASSIGNVERTEX                1078
#define IDB_CONNECT                     1079
#define IDC_BOUND_SUBTRACT              1080
#define IDB_RING                        1081
#define IDB_SELECTRING                  1082
#define IDC_TOGGLE1                     1083
#define IDC_BOUND_TOGGLE                1084
#define IDB_BITMAP10                    1085
#define IDB_SHOWONLY                    1085
#define IDB_BITMAP11                    1086
#define IDB_ADDBONE                     1086
#define IDB_BITMAP12                    1087
#define IDB_LOCK                        1087
#define IDB_BITMAP13                    1088
#define IDB_UNLOCKSELECTED              1088
#define IDB_BITMAP14                    1089
#define IDB_LOCKSELECTED                1089
#define IDB_BITMAP15                    1090
#define IDB_LOCKUNSELECTED              1090
#define IDB_BITMAP16                    1091
#define IDB_UNLOCKALL                   1091
#define IDB_BITMAP17                    1092
#define IDB_BITMAP18                    1093
#define IDB_CREATEMODEL                 1093
#define IDB_BITMAP19                    1094
#define IDB_BITMAP20                    1095
#define IDB_BITMAP21                    1097
#define IDB_PEAK                        1097
#define IDB_BITMAP22                    1098
#define IDB_SMOOTH                      1098
#define IDB_BITMAP23                    1099
#define IDB_TOOGLE_PEAK_SMOOTH          1099
#define IDB_BITMAP24                    1100
#define IDB_SPLITEDGE                   1100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1101
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           1014
#endif
#endif
