//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by perFaceDataMod.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_DYNAPARAMS                  5
#define IDS_SUBOBJ_SEL                  6
#define IDS_INFO                        7
#define IDS_OBJECT                      8
#define IDS_SELECT_OBJECTS              10
#define IDS_ONETOMANY_TOOLTIP           11
#define IDS_NO_ATTRIBUTES               12
#define IDS_FACE_ATTRIBUTES             13
#define IDS_ONETOMANY__REPLACE_TOOLTIP  14
#define IDS_COPY_TOOLTIP                15
#define IDS_CFG_LIST_TOOLTIP            16
#define IDS_BROWSE_TOOLTIP              17
#define IDS_VERTEX                      18
#define IDS_EDGE                        19
#define IDS_FACE                        20
#define IDS_POLY                        21
#define IDS_ELEMENT                     22
#define IDS_OBJECT_SEL                  23
#define IDS_VALUE_NULL                  24
#define IDS_RB_NUMVERTSEL               25
#define IDS_PFD_NUMVERTSEL              26
#define IDS_RB_NUMVERTSELP              27
#define IDS_PFD_NUMVERTSELP             28
#define IDS_RB_NUMFACESELP              29
#define IDS_PFD_NUMFACESELP             30
#define IDS_RB_NUMFACESEL               31
#define IDS_PFD_NUMFACESEL              32
#define IDS_RB_NUMEDGESELP              33
#define IDS_PFD_NUMEDGESELP             33
#define IDS_RB_NUMEDGESEL               34
#define IDS_PFD_NUMEDGESEL              34
#define IDS_EM_OBJECT_SEL               35
#define IDS_PFD_OBJECT_SEL              35
#define IDS_EM_WHICHVERTSEL             36
#define IDS_PFD_WHICHVERTSEL            36
#define IDS_EM_WHICHEDGESEL             37
#define IDS_PFD_WHICHEDGESEL            37
#define IDS_EM_WHICHFACESEL             38
#define IDS_PFD_WHICHFACESEL            38
#define IDS_PFD_ATTRVAL                 39
#define IDS_PFD_ATTRVALS                40
#define IDS_PFD_ATTRVAL_MULTSEL         40
#define IDS_PFD_ATTRVAL_VERTSEL         41
#define IDS_PFD_ATTRVAL_EDGESEL         42
#define IDS_PFD_ATTRASSIGN              49
#define IDS_PFD_ATTRASSIGN_TXT          50
#define IDS_PFD_ATTRQUERY               51
#define IDS_PFD_ATTRQUERY_TXT           52
#define IDS_PFD_ATTRCLEAR               53
#define IDS_PFD_ATTRCLEAR_TXT           54
#define IDS_PFD_ATTRCLEARALL            55
#define IDS_PFD_ATTRCLEARALL_TXT        56
#define IDS_PFD_UNSUPPORTED             69
#define IDS_ATTRIBUTES                  70
#define IDD_PANEL                       101
#define IDD_PANEL_INFO                  102
#define IDD_PANEL_SELECT                103
#define IDB_AVALOGO                     105
#define IDB_SELMASK                     112
#define IDB_SELTYPES                    113
#define IDC_COPYRIGHT_1                 1010
#define IDC_COPYRIGHT_2                 1011
#define IDC_LOGO                        1012
#define IDC_SELTYPE                     1014
#define IDC_IGNORE_BACKFACES_CHK        1015
#define IDC_NORMAL_SHOW                 1016
#define IDC_SHOWNORM_CHK                1016
#define IDC_NORMSCALE_LBL               1017
#define IDC_NORMSCALE_EDIT              1018
#define IDC_NORMSCALE_BOX               1018
#define IDC_NORMALSCALE_SPIN            1019
#define IDC_NORMSCALE_SPIN              1019
#define IDC_NUMSEL_NFO                  1020
#define IDC_IGNORE_VISEDGE_CHK          1021
#define IDC_PLANTHRESH_LBL              1022
#define IDC_PLANTHRESH_EDIT             1023
#define IDC_PLANTHRESH_BOX              1023
#define IDC_PLANTHRESH_SPIN             1024
#define IDC_SUBOBJ_LBL                  1025
#define IDC_SEL_BYVERT_CHK              1025
#define IDC_CUSTOM_ROLLUP               12000
#define IDD_FACEATTRIB                  12001
#define IDC_STATIC_SELOBJECTS           12001
#define IDD_ATTRIBUTES                  12002
#define IDC_ONETOMANY                   12002
#define IDI_REPLACE_DISABLED            12003
#define IDC_REPLACE                     12003
#define IDI_ONETOMANY                   12004
#define IDC_COPY_BUTTON                 12004
#define IDI_ONETOMANY_DISABLED          12005
#define IDC_CFG_LIST                    12005
#define IDI_REPLACE                     12006
#define IDC_BROWSE                      12006
#define IDC_CONFIG_LIST                 12006
#define IDI_COPY_DISABLED               12007
#define IDC_CONFIG_NAME                 12007
#define IDI_COPY                        12008
#define IDC_CONFIG_FILE                 12008
#define IDI_ICON1                       12009
#define IDI_BROWSE                      12009
#define ID_OK_BUTTON                    12009
#define IDD_DIALOG1                     12010
#define ID_CANCEL_BUTTON                12010
#define IDD_CONFIG_FILES                12010
#define ID_NEW_BUTTON                   12011
#define ID_EDIT_BUTTON                  12012
#define ID_DELETE                       12013
#define ID_ACCEPT_BUTTON                12014
#define IDC_BROWSE_FILE_BUTTON          12015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
