#ifndef __DX_VERTEXELEMENT9_H
#define __DX_VERTEXELEMENT9_H

#include "DirectX.h"

typedef enum _D3DDECLTYPE 
{
	D3DDECLTYPE_FLOAT1,
	D3DDECLTYPE_FLOAT2,
	D3DDECLTYPE_FLOAT3,
	D3DDECLTYPE_FLOAT4,
	D3DDECLTYPE_D3DCOLOR,
	D3DDECLTYPE_UBYTE4,
	D3DDECLTYPE_SHORT2,
	D3DDECLTYPE_SHORT4,
	D3DDECLTYPE_UBYTE4N,
	D3DDECLTYPE_SHORT2N,
	D3DDECLTYPE_SHORT4N,
	D3DDECLTYPE_USHORT2N,
	D3DDECLTYPE_USHORT4N,
	D3DDECLTYPE_UDEC3,
	D3DDECLTYPE_DEC3N,
	D3DDECLTYPE_FLOAT16_2,
	D3DDECLTYPE_FLOAT16_4,
	D3DDECLTYPE_UNUSED
} D3DDECLTYPE;

typedef enum _D3DDECLUSAGE 
{
	D3DDECLUSAGE_POSITION = 0,
	D3DDECLUSAGE_BLENDWEIGHT = 1,
	D3DDECLUSAGE_BLENDINDICES = 2,
	D3DDECLUSAGE_NORMAL = 3,
	D3DDECLUSAGE_PSIZE = 4,
	D3DDECLUSAGE_TEXCOORD = 5,
	D3DDECLUSAGE_TANGENT = 6,
	D3DDECLUSAGE_BINORMAL = 7,
	D3DDECLUSAGE_TESSFACTOR = 8,
	D3DDECLUSAGE_POSITIONT = 9,
	D3DDECLUSAGE_COLOR = 10,
	D3DDECLUSAGE_FOG = 11,
	D3DDECLUSAGE_DEPTH = 12,
	D3DDECLUSAGE_SAMPLE = 13
} D3DDECLUSAGE;

typedef struct _D3DVERTEXELEMENT9 
{
	WORD						Stream;
	WORD						Offset;
	BYTE						Type;
	BYTE						Method;
	BYTE						Usage;
	BYTE						UsageIndex;
} D3DVERTEXELEMENT9;

unsigned int numDWORDs( D3DDECLTYPE type );

#endif