#include "stdafx.h"
#include "PropertyTables.h"

PROPERTY_TABLE_START(PropertyTableAggregate)
PROPERTY_TABLE_ENTRY(0,"Aggregate","Tup Aggregate Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","Aggregate Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","Aggregate Name",NULL,NULL,0)
PROPERTY_TABLE_END

SPINNER_VALUES(TestSpinner,0.0f,100.0f,1.0f)

PROPERTY_TABLE_START(PropertyTableScalarInt)
PROPERTY_TABLE_ENTRY(0,"Scalar Int","Tup Scalar Int Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","Scalar Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","Scalar Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_NORMAL(1,"Value","Scalar Int Value",NULL,NULL,0,true)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_SPINNER(2,"Value Spinner","Scalar Int Value Spinner",NULL,NULL,0,TestSpinner)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_CHECKBOX(2,"Bit 0","Bit 0",NULL,NULL,0,"True,False",0x00000001)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_CHECKBOX(2,"Bit 1","Bit 1",NULL,NULL,0,"True,False",0x00000002)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_RADIO_GROUP(2,"Bits 2-3","Bits 2-3",NULL,NULL,0,"0,1,2,3",0x0000000c)
PROPERTY_TABLE_ENTRY_SCALAR_INT_DATA_COMBO_BOX(2,"Bits 4-5","Bits 4-5",NULL,NULL,0,"0,1,2,3",0x00000030)
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableScalarFloat)
PROPERTY_TABLE_ENTRY(0,"Scalar Float","Tup Scalar Float Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","Scalar Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","Scalar Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_SCALAR_FLOAT_DATA_NORMAL(1,"Name","Scalar Name",NULL,NULL,0,6,true)
PROPERTY_TABLE_ENTRY_SCALAR_FLOAT_DATA_SPINNER(1,"Name","Scalar Name",NULL,NULL,0,6,TestSpinner)
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableScalarString)
PROPERTY_TABLE_ENTRY(0,"Scalar String","Tup Scalar String Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","Scalar Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","Scalar Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_SCALAR_STRING_DATA(1,"Value","Value",NULL,NULL,0,true)
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableListInt)
PROPERTY_TABLE_ENTRY(0,"List Int","Tup List Int Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","List Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","List Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_LIST_INT_DATA_GRID(1,"Data","Data",NULL,NULL,0,true,2,true)
PROPERTY_TABLE_ENTRY_LIST_INT_DATA_SUB(1,"Data","Data",NULL,NULL,0,"X|X Value,Y|Y Value,Z|Z Value",true)
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableListFloat)
PROPERTY_TABLE_ENTRY(0,"List Float","Tup List Float Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","List Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","List Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_LIST_FLOAT_DATA_GRID(1,"Data","Data",NULL,NULL,0,6,true,5,true)
PROPERTY_TABLE_ENTRY_LIST_FLOAT_DATA_SUB(1,"Data","Data",NULL,NULL,0,"X|X Value,Y|Y Value,Z|Z Value",6,true)
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableListString)
PROPERTY_TABLE_ENTRY(0,"List String","Tup List String Properties",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","List Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Name","List Name",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_LIST_STRING_DATA_GRID(1,"Data","Data",NULL,NULL,0,2,true)
PROPERTY_TABLE_ENTRY_LIST_STRING_DATA_SUB(1,"Data","Data",NULL,NULL,0,"X|X Value,Y|Y Value,Z|Z Value")
PROPERTY_TABLE_END

PROPERTY_TABLE_START(PropertyTableNode)
PROPERTY_TABLE_ENTRY(0,"Node","Node",0,1)
PROPERTY_TABLE_ENTRY_KEY(1,"Key","Node Key",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_NAME(1,"Reference","Reference",NULL,NULL,0)
PROPERTY_TABLE_ENTRY_SCALAR_STRING_DATA(1,"Name","Name","Name",NULL,0,0)
PROPERTY_TABLE_ENTRY_LIST_FLOAT_DATA_COLOR(1,"Wireframe Color","Wireframe Color","WireframeColor",NULL,0)
PROPERTY_TABLE_END
