// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOGlassDDL_H_
#define _DOGlassDDL_H_

#include <NetZ.h>
#include "NetZTTL/DSGlassState.h"
#include "Network/NetZ/DOActor.h"
#include "NetZTTL/TTLDDF.h"
class DOGlass;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOGlass): public DOActor {
public:
	_DO_DeclareGeneralMethods(DOGlass);

	_DSDECL_DSGlassState	d_state;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOGlass);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOGlass: public DOClassTemplate<DOCLASS(DOGlass), _DOC_DOActor> {
public:
	_DOC_DeclareGeneralMethods(DOGlass)
};
END_NAMESPACE_QUAZAL;

#endif // _DOGlassDDL_H_
