// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOLobbedDDL_H_
#define _DOLobbedDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSVector.h"
#include "NetZTTL/DSLobbedProps.h"
#include "Network/NetZ/DSSixDOF.h"
#include "Network/NetZ/AvalancheProperties.h"
#include "Network/NetZ/DOActor.h"
#include "NetZTTL/TTLDDF.h"
class DOLobbed;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOLobbed): public DOActor {
public:
	_DO_DeclareGeneralMethods(DOLobbed);

	_DSDECL_DSVector	d_acceleration;
	_DSDECL_DSLobbedProps	d_lobbedProps;
	_DSDECL_DSSixDOF	d_state;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOLobbed);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOLobbed: public DOClassTemplate<DOCLASS(DOLobbed), _DOC_DOActor> {
public:
	_DOC_DeclareGeneralMethods(DOLobbed)
};
END_NAMESPACE_QUAZAL;

#endif // _DOLobbedDDL_H_
