// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOPlayerAgentDDL_H_
#define _DOPlayerAgentDDL_H_

#include <NetZ.h>
#include "NetZTTL/DSAgent.h"
#include "NetZTTL/DSAppearance.h"
#include "NetZTTL/DSLevel.h"
#include "NetZTTL/DSParticipant.h"
#include "NetZTTL/DSProfile.h"
#include "NetZTTL/DSStats.h"
#include "Network/NetZ/DOTalker.h"
#include "NetZTTL/TTLDDF.h"
class DOPlayerAgent;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOPlayerAgent): public DOTalker {
public:
	_DO_DeclareGeneralMethods(DOPlayerAgent);

	_DSDECL_DSAgent	d_agent;
	_DSDECL_DSAppearance	d_appearance;
	_DSDECL_DSLevel	d_level;
	_DSDECL_DSParticipant	d_participant;
	_DSDECL_DSProfile	d_profile;
	_DSDECL_DSStats	d_stats;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOPlayerAgent);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOPlayerAgent: public DOClassTemplate<DOCLASS(DOPlayerAgent), _DOC_DOTalker> {
public:
	_DOC_DeclareGeneralMethods(DOPlayerAgent)
};
END_NAMESPACE_QUAZAL;

#endif // _DOPlayerAgentDDL_H_
