// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSAgentDDL_H_
#define _DSAgentDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSAgent): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSAgent);
	DATASET(DSAgent)( const DATASET(DSAgent) &oOther ) :
		d_lobbyStatus(oOther.d_lobbyStatus), 
		d_mode(oOther.d_mode)
	{
	}

	_DS_ASSIGN_OPERATOR(DSAgent){
		_DS_COPYDATASET_VAR(d_lobbyStatus);
		_DS_COPYDATASET_VAR(d_mode);
	}

	_DS_EQUAL_OPERATOR(DSAgent){
		_DS_EQUAL_VAR(d_lobbyStatus);
		_DS_EQUAL_VAR(d_mode);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSAgent)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_lobbyStatus,d_lobbyStatus);
		_MSG_EXTRACT_VARIABLE(Td_mode,d_mode);
	}

	DDLTYPE(byte)::CPPType d_lobbyStatus;
	DDLTYPE(byte)::CPPType d_mode;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_lobbyStatus;
	typedef DDLTYPE(byte) Td_mode;
};

#define _DSDECL_DSAgent DSAgent

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSAgent);


#endif // _DSAgentDDL_H_
