// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSAgent.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSAgent);
_PR_upon_request_filter_impl(DSAgent);

	qBool DATASET(DSAgent)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_lobbyStatus,d_lobbyStatus);
		_DS_FormatMatchingVariableValue(Td_mode,d_mode);
		return false;
	}

	void DATASET(DSAgent)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_lobbyStatus,d_lobbyStatus);
		_MSG_ADD_VARIABLE(Td_mode,d_mode);
	}

END_NAMESPACE_QUAZAL;
