// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSAppearance.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSAppearance);
_PR_upon_request_filter_impl(DSAppearance);

	qBool DATASET(DSAppearance)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_character,d_character);
		_DS_FormatMatchingVariableValue(Td_loadout,d_loadout);
		return false;
	}

	void DATASET(DSAppearance)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_character,d_character);
		_MSG_ADD_VARIABLE(Td_loadout,d_loadout);
	}

END_NAMESPACE_QUAZAL;
