// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSAppearanceDDL_H_
#define _DSAppearanceDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSAppearance): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSAppearance);
	DATASET(DSAppearance)( const DATASET(DSAppearance) &oOther ) :
		d_character(oOther.d_character), 
		d_loadout(oOther.d_loadout)
	{
	}

	_DS_ASSIGN_OPERATOR(DSAppearance){
		_DS_COPYDATASET_VAR(d_character);
		_DS_COPYDATASET_VAR(d_loadout);
	}

	_DS_EQUAL_OPERATOR(DSAppearance){
		_DS_EQUAL_VAR(d_character);
		_DS_EQUAL_VAR(d_loadout);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSAppearance)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_character,d_character);
		_MSG_EXTRACT_VARIABLE(Td_loadout,d_loadout);
	}

	DDLTYPE(string)::CPPType d_character;
	DDLTYPE(string)::CPPType d_loadout;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(string) Td_character;
	typedef DDLTYPE(string) Td_loadout;
};

#define _DSDECL_DSAppearance DSAppearance

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSAppearance);


#endif // _DSAppearanceDDL_H_
