// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSCombatantModeDDL_H_
#define _DSCombatantModeDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSCombatantMode): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSCombatantMode);
	DATASET(DSCombatantMode)( const DATASET(DSCombatantMode) &oOther ) :
		d_flags(oOther.d_flags), 
		d_health(oOther.d_health), 
		d_painState(oOther.d_painState), 
		d_weapon(oOther.d_weapon)
	{
	}

	_DS_ASSIGN_OPERATOR(DSCombatantMode){
		_DS_COPYDATASET_VAR(d_flags);
		_DS_COPYDATASET_VAR(d_health);
		_DS_COPYDATASET_VAR(d_painState);
		_DS_COPYDATASET_VAR(d_weapon);
	}

	_DS_EQUAL_OPERATOR(DSCombatantMode){
		_DS_EQUAL_VAR(d_flags);
		_DS_EQUAL_VAR(d_health);
		_DS_EQUAL_VAR(d_painState);
		_DS_EQUAL_VAR(d_weapon);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSCombatantMode)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_flags,d_flags);
		_MSG_EXTRACT_VARIABLE(Td_health,d_health);
		_MSG_EXTRACT_VARIABLE(Td_painState,d_painState);
		_MSG_EXTRACT_VARIABLE(Td_weapon,d_weapon);
	}

	DDLTYPE(byte)::CPPType d_flags;
	DDLTYPE(byte)::CPPType d_health;
	DDLTYPE(int32)::CPPType d_painState;
	DDLTYPE(byte)::CPPType d_weapon;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_flags;
	typedef DDLTYPE(byte) Td_health;
	typedef DDLTYPE(int32) Td_painState;
	typedef DDLTYPE(byte) Td_weapon;
};

#define _DSDECL_DSCombatantMode DSCombatantMode

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSCombatantMode);


#endif // _DSCombatantModeDDL_H_
