// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSCombatantMode.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSCombatantMode);
_PR_upon_request_filter_impl(DSCombatantMode);

	qBool DATASET(DSCombatantMode)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_flags,d_flags);
		_DS_FormatMatchingVariableValue(Td_health,d_health);
		_DS_FormatMatchingVariableValue(Td_painState,d_painState);
		_DS_FormatMatchingVariableValue(Td_weapon,d_weapon);
		return false;
	}

	void DATASET(DSCombatantMode)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_flags,d_flags);
		_MSG_ADD_VARIABLE(Td_health,d_health);
		_MSG_ADD_VARIABLE(Td_painState,d_painState);
		_MSG_ADD_VARIABLE(Td_weapon,d_weapon);
	}

END_NAMESPACE_QUAZAL;
