// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSCombatantState.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSCombatantState);
	_DS_IMPLEMENT_EXTRAPOLATED(DSCombatantState);
_PR_unreliable_impl(DSCombatantState);
_PR_extrapolation_filter_impl(DSCombatantState);

	qBool DATASET(DSCombatantState)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_sightX,d_sightX);
		_DS_FormatMatchingVariableValue(Td_sightY,d_sightY);
		_DS_FormatMatchingVariableValue(Td_sightZ,d_sightZ);
		return false;
	}

	void DATASET(DSCombatantState)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_DS_ADD_TIMESTAMP();
		_DS_ADD_BREAK();
		_MSG_ADD_VARIABLE(Td_sightX,d_sightX);
		_MSG_ADD_VARIABLE(Td_sightY,d_sightY);
		_MSG_ADD_VARIABLE(Td_sightZ,d_sightZ);
	}

END_NAMESPACE_QUAZAL;
