// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSGlassStateDDL_H_
#define _DSGlassStateDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSGlassState): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSGlassState);
	DATASET(DSGlassState)( const DATASET(DSGlassState) &oOther ) :
		d_shattered(oOther.d_shattered)
	{
	}

	_DS_ASSIGN_OPERATOR(DSGlassState){
		_DS_COPYDATASET_VAR(d_shattered);
	}

	_DS_EQUAL_OPERATOR(DSGlassState){
		_DS_EQUAL_VAR(d_shattered);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSGlassState)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_shattered,d_shattered);
	}

	DDLTYPE(bool)::CPPType d_shattered;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(bool) Td_shattered;
};

#define _DSDECL_DSGlassState DSGlassState

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSGlassState);


#endif // _DSGlassStateDDL_H_
