// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSLevel.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSLevel);
_PR_upon_request_filter_impl(DSLevel);

	qBool DATASET(DSLevel)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_centerX,d_centerX);
		_DS_FormatMatchingVariableValue(Td_centerY,d_centerY);
		_DS_FormatMatchingVariableValue(Td_centerZ,d_centerZ);
		_DS_FormatMatchingVariableValue(Td_crc,d_crc);
		_DS_FormatMatchingVariableValue(Td_distributedActorCount,d_distributedActorCount);
		_DS_FormatMatchingVariableValue(Td_extentX,d_extentX);
		_DS_FormatMatchingVariableValue(Td_extentY,d_extentY);
		_DS_FormatMatchingVariableValue(Td_extentZ,d_extentZ);
		return false;
	}

	void DATASET(DSLevel)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_centerX,d_centerX);
		_MSG_ADD_VARIABLE(Td_centerY,d_centerY);
		_MSG_ADD_VARIABLE(Td_centerZ,d_centerZ);
		_MSG_ADD_VARIABLE(Td_crc,d_crc);
		_MSG_ADD_VARIABLE(Td_distributedActorCount,d_distributedActorCount);
		_MSG_ADD_VARIABLE(Td_extentX,d_extentX);
		_MSG_ADD_VARIABLE(Td_extentY,d_extentY);
		_MSG_ADD_VARIABLE(Td_extentZ,d_extentZ);
	}

END_NAMESPACE_QUAZAL;
