// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSLevelDDL_H_
#define _DSLevelDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSLevel): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSLevel);
	DATASET(DSLevel)( const DATASET(DSLevel) &oOther ) :
		d_centerX(oOther.d_centerX), 
		d_centerY(oOther.d_centerY), 
		d_centerZ(oOther.d_centerZ), 
		d_crc(oOther.d_crc), 
		d_distributedActorCount(oOther.d_distributedActorCount), 
		d_extentX(oOther.d_extentX), 
		d_extentY(oOther.d_extentY), 
		d_extentZ(oOther.d_extentZ)
	{
	}

	_DS_ASSIGN_OPERATOR(DSLevel){
		_DS_COPYDATASET_VAR(d_centerX);
		_DS_COPYDATASET_VAR(d_centerY);
		_DS_COPYDATASET_VAR(d_centerZ);
		_DS_COPYDATASET_VAR(d_crc);
		_DS_COPYDATASET_VAR(d_distributedActorCount);
		_DS_COPYDATASET_VAR(d_extentX);
		_DS_COPYDATASET_VAR(d_extentY);
		_DS_COPYDATASET_VAR(d_extentZ);
	}

	_DS_EQUAL_OPERATOR(DSLevel){
		_DS_EQUAL_VAR(d_centerX);
		_DS_EQUAL_VAR(d_centerY);
		_DS_EQUAL_VAR(d_centerZ);
		_DS_EQUAL_VAR(d_crc);
		_DS_EQUAL_VAR(d_distributedActorCount);
		_DS_EQUAL_VAR(d_extentX);
		_DS_EQUAL_VAR(d_extentY);
		_DS_EQUAL_VAR(d_extentZ);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSLevel)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_centerX,d_centerX);
		_MSG_EXTRACT_VARIABLE(Td_centerY,d_centerY);
		_MSG_EXTRACT_VARIABLE(Td_centerZ,d_centerZ);
		_MSG_EXTRACT_VARIABLE(Td_crc,d_crc);
		_MSG_EXTRACT_VARIABLE(Td_distributedActorCount,d_distributedActorCount);
		_MSG_EXTRACT_VARIABLE(Td_extentX,d_extentX);
		_MSG_EXTRACT_VARIABLE(Td_extentY,d_extentY);
		_MSG_EXTRACT_VARIABLE(Td_extentZ,d_extentZ);
	}

	DDLTYPE(float)::CPPType d_centerX;
	DDLTYPE(float)::CPPType d_centerY;
	DDLTYPE(float)::CPPType d_centerZ;
	DDLTYPE(uint32)::CPPType d_crc;
	DDLTYPE(int32)::CPPType d_distributedActorCount;
	DDLTYPE(float)::CPPType d_extentX;
	DDLTYPE(float)::CPPType d_extentY;
	DDLTYPE(float)::CPPType d_extentZ;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(float) Td_centerX;
	typedef DDLTYPE(float) Td_centerY;
	typedef DDLTYPE(float) Td_centerZ;
	typedef DDLTYPE(uint32) Td_crc;
	typedef DDLTYPE(int32) Td_distributedActorCount;
	typedef DDLTYPE(float) Td_extentX;
	typedef DDLTYPE(float) Td_extentY;
	typedef DDLTYPE(float) Td_extentZ;
};

#define _DSDECL_DSLevel DSLevel

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSLevel);


#endif // _DSLevelDDL_H_
