// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSLobbedProps.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSLobbedProps);

	qBool DATASET(DSLobbedProps)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_type,d_type);
		return false;
	}

	void DATASET(DSLobbedProps)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_type,d_type);
	}

END_NAMESPACE_QUAZAL;
