// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSLobbedPropsDDL_H_
#define _DSLobbedPropsDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSLobbedProps): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSLobbedProps);
	DATASET(DSLobbedProps)( const DATASET(DSLobbedProps) &oOther ) :
		d_type(oOther.d_type)
	{
	}

	_DS_ASSIGN_OPERATOR(DSLobbedProps){
		_DS_COPYDATASET_VAR(d_type);
	}

	_DS_EQUAL_OPERATOR(DSLobbedProps){
		_DS_EQUAL_VAR(d_type);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSLobbedProps)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_type,d_type);
	}

	DDLTYPE(int32)::CPPType d_type;

protected:
private:
	typedef DDLTYPE(int32) Td_type;
};

#define _DSDECL_DSLobbedProps DSLobbedProps

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSLobbedProps);


#endif // _DSLobbedPropsDDL_H_
