// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSParticipantDDL_H_
#define _DSParticipantDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSParticipant): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSParticipant);
	DATASET(DSParticipant)( const DATASET(DSParticipant) &oOther ) :
		d_config(oOther.d_config), 
		d_id(oOther.d_id)
	{
	}

	_DS_ASSIGN_OPERATOR(DSParticipant){
		_DS_COPYDATASET_VAR(d_config);
		_DS_COPYDATASET_VAR(d_id);
	}

	_DS_EQUAL_OPERATOR(DSParticipant){
		_DS_EQUAL_VAR(d_config);
		_DS_EQUAL_VAR(d_id);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSParticipant)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_config,d_config);
		_MSG_EXTRACT_VARIABLE(Td_id,d_id);
	}

	DDLTYPE(byte)::CPPType d_config;
	DDLTYPE(byte)::CPPType d_id;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_config;
	typedef DDLTYPE(byte) Td_id;
};

#define _DSDECL_DSParticipant DSParticipant

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSParticipant);


#endif // _DSParticipantDDL_H_
