// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSParticipant.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSParticipant);
_PR_upon_request_filter_impl(DSParticipant);

	qBool DATASET(DSParticipant)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_config,d_config);
		_DS_FormatMatchingVariableValue(Td_id,d_id);
		return false;
	}

	void DATASET(DSParticipant)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_config,d_config);
		_MSG_ADD_VARIABLE(Td_id,d_id);
	}

END_NAMESPACE_QUAZAL;
