// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSProfileDDL_H_
#define _DSProfileDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSProfile): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSProfile);
	DATASET(DSProfile)( const DATASET(DSProfile) &oOther ) :
		d_accountName(oOther.d_accountName), 
		d_displayName(oOther.d_displayName)
	{
		_DS_COPYDATASET_ARRAY(d_accountId,16);
		_DS_COPYDATASET_ARRAY(d_tagParams,32);
	}

	_DS_ASSIGN_OPERATOR(DSProfile){
		_DS_COPYDATASET_ARRAY(d_accountId,16);
		_DS_COPYDATASET_VAR(d_accountName);
		_DS_COPYDATASET_VAR(d_displayName);
		_DS_COPYDATASET_ARRAY(d_tagParams,32);
	}

	_DS_EQUAL_OPERATOR(DSProfile){
		_DS_EQUAL_ARRAY(d_accountId,16);
		_DS_EQUAL_VAR(d_accountName);
		_DS_EQUAL_VAR(d_displayName);
		_DS_EQUAL_ARRAY(d_tagParams,32);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSProfile)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_accountId,d_accountId,16);
		_MSG_EXTRACT_VARIABLE(Td_accountName,d_accountName);
		_MSG_EXTRACT_VARIABLE(Td_displayName,d_displayName);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_tagParams,d_tagParams,32);
	}

	DDLTYPE(byte)::CPPType d_accountId[16];
	DDLTYPE(string)::CPPType d_accountName;
	DDLTYPE(string)::CPPType d_displayName;
	DDLTYPE(byte)::CPPType d_tagParams[32];

protected:
private:
	typedef DDLTYPE(byte) Td_accountId;
	typedef DDLTYPE(string) Td_accountName;
	typedef DDLTYPE(string) Td_displayName;
	typedef DDLTYPE(byte) Td_tagParams;
};

#define _DSDECL_DSProfile DSProfile

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSProfile);


#endif // _DSProfileDDL_H_
