// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSRefereePopulate.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSRefereePopulate);
_PR_upon_request_filter_impl(DSRefereePopulate);

	qBool DATASET(DSRefereePopulate)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_crc,d_crc);
		_DS_FormatMatchingVariableValue(Td_numPlayers,d_numPlayers);
		return false;
	}

	void DATASET(DSRefereePopulate)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_crc,d_crc);
		_MSG_ADD_VARIABLE_ARRAY(Td_end,d_end,16);
		_MSG_ADD_VARIABLE(Td_numPlayers,d_numPlayers);
		_MSG_ADD_VARIABLE_ARRAY(Td_start,d_start,16);
	}

END_NAMESPACE_QUAZAL;
