// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSRefereeRound.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSRefereeRound);
_PR_upon_request_filter_impl(DSRefereeRound);

	qBool DATASET(DSRefereeRound)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_status,d_status);
		return false;
	}

	void DATASET(DSRefereeRound)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE_ARRAY(Td_roundId,d_roundId,8);
		_MSG_ADD_VARIABLE(Td_status,d_status);
	}

END_NAMESPACE_QUAZAL;
