// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSRefereeRoundDDL_H_
#define _DSRefereeRoundDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSRefereeRound): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSRefereeRound);
	DATASET(DSRefereeRound)( const DATASET(DSRefereeRound) &oOther ) :
		d_status(oOther.d_status)
	{
		_DS_COPYDATASET_ARRAY(d_roundId,8);
	}

	_DS_ASSIGN_OPERATOR(DSRefereeRound){
		_DS_COPYDATASET_ARRAY(d_roundId,8);
		_DS_COPYDATASET_VAR(d_status);
	}

	_DS_EQUAL_OPERATOR(DSRefereeRound){
		_DS_EQUAL_ARRAY(d_roundId,8);
		_DS_EQUAL_VAR(d_status);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSRefereeRound)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_roundId,d_roundId,8);
		_MSG_EXTRACT_VARIABLE(Td_status,d_status);
	}

	DDLTYPE(byte)::CPPType d_roundId[8];
	DDLTYPE(byte)::CPPType d_status;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_roundId;
	typedef DDLTYPE(byte) Td_status;
};

#define _DSDECL_DSRefereeRound DSRefereeRound

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSRefereeRound);


#endif // _DSRefereeRoundDDL_H_
