// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSRefereePhase.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSRefereePhase);
_PR_upon_request_filter_impl(DSRefereePhase);

	qBool DATASET(DSRefereePhase)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_assignmentId,d_assignmentId);
		_DS_FormatMatchingVariableValue(Td_changeTime,d_changeTime);
		_DS_FormatMatchingVariableValue(Td_value,d_value);
		return false;
	}

	void DATASET(DSRefereePhase)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_assignmentId,d_assignmentId);
		_MSG_ADD_VARIABLE(Td_changeTime,d_changeTime);
		_MSG_ADD_VARIABLE(Td_value,d_value);
	}

END_NAMESPACE_QUAZAL;
