// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSRefereeRulesDDL_H_
#define _DSRefereeRulesDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSRefereeRules): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSRefereeRules);
	DATASET(DSRefereeRules)( const DATASET(DSRefereeRules) &oOther ) :
		d_desc(oOther.d_desc)
	{
		_DS_COPYDATASET_ARRAY(d_teamRole,8);
	}

	_DS_ASSIGN_OPERATOR(DSRefereeRules){
		_DS_COPYDATASET_VAR(d_desc);
		_DS_COPYDATASET_ARRAY(d_teamRole,8);
	}

	_DS_EQUAL_OPERATOR(DSRefereeRules){
		_DS_EQUAL_VAR(d_desc);
		_DS_EQUAL_ARRAY(d_teamRole,8);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSRefereeRules)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_desc,d_desc);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_teamRole,d_teamRole,8);
	}

	DDLTYPE(string)::CPPType d_desc;
	DDLTYPE(byte)::CPPType d_teamRole[8];
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(string) Td_desc;
	typedef DDLTYPE(byte) Td_teamRole;
};

#define _DSDECL_DSRefereeRules DSRefereeRules

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSRefereeRules);


#endif // _DSRefereeRulesDDL_H_
