// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSRefereePopulateDDL_H_
#define _DSRefereePopulateDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSRefereePopulate): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSRefereePopulate);
	DATASET(DSRefereePopulate)( const DATASET(DSRefereePopulate) &oOther ) :
		d_crc(oOther.d_crc), 
		d_numPlayers(oOther.d_numPlayers)
	{
		_DS_COPYDATASET_ARRAY(d_end,16);
		_DS_COPYDATASET_ARRAY(d_start,16);
	}

	_DS_ASSIGN_OPERATOR(DSRefereePopulate){
		_DS_COPYDATASET_VAR(d_crc);
		_DS_COPYDATASET_ARRAY(d_end,16);
		_DS_COPYDATASET_VAR(d_numPlayers);
		_DS_COPYDATASET_ARRAY(d_start,16);
	}

	_DS_EQUAL_OPERATOR(DSRefereePopulate){
		_DS_EQUAL_VAR(d_crc);
		_DS_EQUAL_ARRAY(d_end,16);
		_DS_EQUAL_VAR(d_numPlayers);
		_DS_EQUAL_ARRAY(d_start,16);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSRefereePopulate)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_crc,d_crc);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_end,d_end,16);
		_MSG_EXTRACT_VARIABLE(Td_numPlayers,d_numPlayers);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_start,d_start,16);
	}

	DDLTYPE(uint32)::CPPType d_crc;
	DDLTYPE(int32)::CPPType d_end[16];
	DDLTYPE(uint32)::CPPType d_numPlayers;
	DDLTYPE(int32)::CPPType d_start[16];
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(uint32) Td_crc;
	typedef DDLTYPE(int32) Td_end;
	typedef DDLTYPE(uint32) Td_numPlayers;
	typedef DDLTYPE(int32) Td_start;
};

#define _DSDECL_DSRefereePopulate DSRefereePopulate

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSRefereePopulate);


#endif // _DSRefereePopulateDDL_H_
