// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSRefereeAssignment.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSRefereeAssignment);
_PR_upon_request_filter_impl(DSRefereeAssignment);

	qBool DATASET(DSRefereeAssignment)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_assignmentId,d_assignmentId);
		return false;
	}

	void DATASET(DSRefereeAssignment)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_assignmentId,d_assignmentId);
		_MSG_ADD_VARIABLE_ARRAY(Td_config,d_config,56);
	}

END_NAMESPACE_QUAZAL;
