// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSRefereePhaseDDL_H_
#define _DSRefereePhaseDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSRefereePhase): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSRefereePhase);
	DATASET(DSRefereePhase)( const DATASET(DSRefereePhase) &oOther ) :
		d_assignmentId(oOther.d_assignmentId), 
		d_changeTime(oOther.d_changeTime), 
		d_value(oOther.d_value)
	{
	}

	_DS_ASSIGN_OPERATOR(DSRefereePhase){
		_DS_COPYDATASET_VAR(d_assignmentId);
		_DS_COPYDATASET_VAR(d_changeTime);
		_DS_COPYDATASET_VAR(d_value);
	}

	_DS_EQUAL_OPERATOR(DSRefereePhase){
		_DS_EQUAL_VAR(d_assignmentId);
		_DS_EQUAL_VAR(d_changeTime);
		_DS_EQUAL_VAR(d_value);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSRefereePhase)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_assignmentId,d_assignmentId);
		_MSG_EXTRACT_VARIABLE(Td_changeTime,d_changeTime);
		_MSG_EXTRACT_VARIABLE(Td_value,d_value);
	}

	DDLTYPE(byte)::CPPType d_assignmentId;
	DDLTYPE(int32)::CPPType d_changeTime;
	DDLTYPE(byte)::CPPType d_value;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_assignmentId;
	typedef DDLTYPE(int32) Td_changeTime;
	typedef DDLTYPE(byte) Td_value;
};

#define _DSDECL_DSRefereePhase DSRefereePhase

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSRefereePhase);


#endif // _DSRefereePhaseDDL_H_
