// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSRefereeRules.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSRefereeRules);
_PR_upon_request_filter_impl(DSRefereeRules);

	qBool DATASET(DSRefereeRules)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_desc,d_desc);
		return false;
	}

	void DATASET(DSRefereeRules)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_desc,d_desc);
		_MSG_ADD_VARIABLE_ARRAY(Td_teamRole,d_teamRole,8);
	}

END_NAMESPACE_QUAZAL;
