// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSRefereeIdDDL_H_
#define _DSRefereeIdDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSRefereeId): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSRefereeId);
	DATASET(DSRefereeId)( const DATASET(DSRefereeId) &oOther )
	{
		_DS_COPYDATASET_ARRAY(d_handle,56);
	}

	_DS_ASSIGN_OPERATOR(DSRefereeId){
		_DS_COPYDATASET_ARRAY(d_handle,56);
	}

	_DS_EQUAL_OPERATOR(DSRefereeId){
		_DS_EQUAL_ARRAY(d_handle,56);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSRefereeId)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_handle,d_handle,56);
	}

	DDLTYPE(dohandle)::CPPType d_handle[56];
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(dohandle) Td_handle;
};

#define _DSDECL_DSRefereeId DSRefereeId

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSRefereeId);


#endif // _DSRefereeIdDDL_H_
