// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSScoringPlayerInfoDDL_H_
#define _DSScoringPlayerInfoDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSScoringPlayerInfo): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSScoringPlayerInfo);
	DATASET(DSScoringPlayerInfo)( const DATASET(DSScoringPlayerInfo) &oOther ) :
		d_isAlphaBlue(oOther.d_isAlphaBlue)
	{
		_DS_COPYDATASET_ARRAY(d_name,16);
		_DS_COPYDATASET_ARRAY(d_team,16);
	}

	_DS_ASSIGN_OPERATOR(DSScoringPlayerInfo){
		_DS_COPYDATASET_VAR(d_isAlphaBlue);
		_DS_COPYDATASET_ARRAY(d_name,16);
		_DS_COPYDATASET_ARRAY(d_team,16);
	}

	_DS_EQUAL_OPERATOR(DSScoringPlayerInfo){
		_DS_EQUAL_VAR(d_isAlphaBlue);
		_DS_EQUAL_ARRAY(d_name,16);
		_DS_EQUAL_ARRAY(d_team,16);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSScoringPlayerInfo)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_isAlphaBlue,d_isAlphaBlue);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_name,d_name,16);
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_team,d_team,16);
	}

	DDLTYPE(byte)::CPPType d_isAlphaBlue;
	DDLTYPE(string)::CPPType d_name[16];
	DDLTYPE(byte)::CPPType d_team[16];
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(byte) Td_isAlphaBlue;
	typedef DDLTYPE(string) Td_name;
	typedef DDLTYPE(byte) Td_team;
};

#define _DSDECL_DSScoringPlayerInfo DSScoringPlayerInfo

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSScoringPlayerInfo);


#endif // _DSScoringPlayerInfoDDL_H_
