// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSSessionDDL_H_
#define _DSSessionDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSSession): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSSession);
	DATASET(DSSession)( const DATASET(DSSession) &oOther ) :
		d_alphaWins(oOther.d_alphaWins), 
		d_betaWins(oOther.d_betaWins)
	{
	}

	_DS_ASSIGN_OPERATOR(DSSession){
		_DS_COPYDATASET_VAR(d_alphaWins);
		_DS_COPYDATASET_VAR(d_betaWins);
	}

	_DS_EQUAL_OPERATOR(DSSession){
		_DS_EQUAL_VAR(d_alphaWins);
		_DS_EQUAL_VAR(d_betaWins);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSSession)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_alphaWins,d_alphaWins);
		_MSG_EXTRACT_VARIABLE(Td_betaWins,d_betaWins);
	}

	DDLTYPE(int32)::CPPType d_alphaWins;
	DDLTYPE(int32)::CPPType d_betaWins;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(int32) Td_alphaWins;
	typedef DDLTYPE(int32) Td_betaWins;
};

#define _DSDECL_DSSession DSSession

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSSession);


#endif // _DSSessionDDL_H_
