// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSSession.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSSession);
_PR_upon_request_filter_impl(DSSession);

	qBool DATASET(DSSession)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_alphaWins,d_alphaWins);
		_DS_FormatMatchingVariableValue(Td_betaWins,d_betaWins);
		return false;
	}

	void DATASET(DSSession)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_alphaWins,d_alphaWins);
		_MSG_ADD_VARIABLE(Td_betaWins,d_betaWins);
	}

END_NAMESPACE_QUAZAL;
