// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSStatsDDL_H_
#define _DSStatsDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSStats): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSStats);
	DATASET(DSStats)( const DATASET(DSStats) &oOther ) :
		d_rank(oOther.d_rank), 
		d_rating(oOther.d_rating)
	{
	}

	_DS_ASSIGN_OPERATOR(DSStats){
		_DS_COPYDATASET_VAR(d_rank);
		_DS_COPYDATASET_VAR(d_rating);
	}

	_DS_EQUAL_OPERATOR(DSStats){
		_DS_EQUAL_VAR(d_rank);
		_DS_EQUAL_VAR(d_rating);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSStats)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_rank,d_rank);
		_MSG_EXTRACT_VARIABLE(Td_rating,d_rating);
	}

	DDLTYPE(int32)::CPPType d_rank;
	DDLTYPE(int32)::CPPType d_rating;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(int32) Td_rank;
	typedef DDLTYPE(int32) Td_rating;
};

#define _DSDECL_DSStats DSStats

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSStats);


#endif // _DSStatsDDL_H_
