// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSStats.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSStats);
_PR_upon_request_filter_impl(DSStats);

	qBool DATASET(DSStats)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_rank,d_rank);
		_DS_FormatMatchingVariableValue(Td_rating,d_rating);
		return false;
	}

	void DATASET(DSStats)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_rank,d_rank);
		_MSG_ADD_VARIABLE(Td_rating,d_rating);
	}

END_NAMESPACE_QUAZAL;
