// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSSubsonicPropsDDL_H_
#define _DSSubsonicPropsDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSSubsonicProps): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSSubsonicProps);
	DATASET(DSSubsonicProps)( const DATASET(DSSubsonicProps) &oOther ) :
		d_type(oOther.d_type)
	{
	}

	_DS_ASSIGN_OPERATOR(DSSubsonicProps){
		_DS_COPYDATASET_VAR(d_type);
	}

	_DS_EQUAL_OPERATOR(DSSubsonicProps){
		_DS_EQUAL_VAR(d_type);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSSubsonicProps)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_type,d_type);
	}

	DDLTYPE(int32)::CPPType d_type;

protected:
private:
	typedef DDLTYPE(int32) Td_type;
};

#define _DSDECL_DSSubsonicProps DSSubsonicProps

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSSubsonicProps);


#endif // _DSSubsonicPropsDDL_H_
