// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSTeamsDDL_H_
#define _DSTeamsDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSTeams): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSTeams);
	DATASET(DSTeams)( const DATASET(DSTeams) &oOther )
	{
		_DS_COPYDATASET_ARRAY(d_spawnTickets,8);
	}

	_DS_ASSIGN_OPERATOR(DSTeams){
		_DS_COPYDATASET_ARRAY(d_spawnTickets,8);
	}

	_DS_EQUAL_OPERATOR(DSTeams){
		_DS_EQUAL_ARRAY(d_spawnTickets,8);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSTeams)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE_ARRAY(Td_spawnTickets,d_spawnTickets,8);
	}

	DDLTYPE(uint16)::CPPType d_spawnTickets[8];
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(uint16) Td_spawnTickets;
};

#define _DSDECL_DSTeams DSTeams

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSTeams);


#endif // _DSTeamsDDL_H_
