// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "TTLPCH.h"
#include "NetZTTL/DSTeams.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSTeams);
_PR_upon_request_filter_impl(DSTeams);

	qBool DATASET(DSTeams)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		DUMMY_PARAM(pVariable);
		DUMMY_PARAM(pstrResult);
		return false;
	}

	void DATASET(DSTeams)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE_ARRAY(Td_spawnTickets,d_spawnTickets,8);
	}

END_NAMESPACE_QUAZAL;
