//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Pigpen.rc
//
#define IDC_MODEL_LOAD                  3
#define IDC_MODEL_CLEAR                 4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EFFECTVIEW                  129
#define IDR_VIEW                        129
#define IDR_POPUP_MENUS                 130
#define IDD_EFFECT_DIALOG               132
#define IDR_ELEMENTVIEW                 134
#define IDD_ELEMENT_DIALOG              135
#define IDD_PAGE_DISPLAY                135
#define IDD_GRAPHIC_DIALOG              137
#define IDD_IMPORT_DIALOG               138
#define IDD_PAGE_MOVEMENT               139
#define IDD_PAGE_COLLISION              140
#define IDD_PAGE_COLLIDE                140
#define IDD_PAGE_SIZE                   141
#define IDD_ENVELOPE_DIALOG             142
#define IDD_PAGE_ENVELOPE               142
#define IDD_PREVIEW_DIALOG              143
#define IDD_PAGE_COLOR                  146
#define IDD_EMITTER_DIALOG              147
#define IDD_EMITTER_MODEL_DIALOG        148
#define IDD_PROGRESS                    149
#define IDD_PAGE_LIFETIME               150
#define IDD_SURFACE_LIST                151
#define IDD_PAGE_PIGGYBACK              152
#define IDD_PAGE_SWOOSH_DISPLAY         153
#define IDD_SWOOSH_EMITTER_DIALOG       154
#define IDC_ELEMENT_C1                  1002
#define IDC_PARTICLE_C1                 1002
#define IDC_ELEMENT_C2                  1003
#define IDC_PARTICLE_C2                 1003
#define IDC_CHANNEL                     1003
#define IDC_ELEMENT_C3                  1004
#define IDC_PARTICLE_C3                 1004
#define IDC_ELEMENT_C4                  1005
#define IDC_PARTICLE_C4                 1005
#define IDC_ELEMENT_C5                  1006
#define IDC_PARTICLE_C5                 1006
#define IDC_COUNT_E1                    1007
#define IDC_COUNT_E2                    1008
#define IDC_COUNT_E3                    1009
#define IDC_COUNT_E4                    1010
#define IDC_COUNT_E5                    1011
#define IDC_COUNT_S1                    1015
#define IDC_COUNT_S2                    1016
#define IDC_COUNT_S3                    1017
#define IDC_COUNT_S4                    1018
#define IDC_COUNT_S5                    1019
#define IDC_COUNT_RANDOM_S1             1020
#define IDC_DELAY1_S1                   1021
#define IDC_DELAY1_RANDOM_S1            1022
#define IDC_DELAY2_S1                   1023
#define IDC_DELAY2_RANDOM_S1            1024
#define IDC_COUNT_RANDOM_E1             1025
#define IDC_DELAY1_E1                   1026
#define IDC_DELAY_E1                    1026
#define IDC_PICTURE_P1                  1027
#define IDC_DIAGRAM_B1                  1027
#define IDC_DELAY1_RANDOM_E1            1028
#define IDC_DELAY_RANDOM_E1             1028
#define IDC_DELAY2_E1                   1029
#define IDC_TIME_E1                     1029
#define IDC_DELAY2_RANDOM_E1            1030
#define IDC_TIME_RANDOM_E1              1030
#define IDC_COUNT_RANDOM_E2             1031
#define IDC_DIAGRAM_B6                  1031
#define IDC_COUNT_RANDOM_S2             1032
#define IDC_DELAY_E2                    1033
#define IDC_DELAY1_S2                   1034
#define IDC_DELAY_RANDOM_E2             1035
#define IDC_REVERT                      1036
#define IDC_RESTORE                     1036
#define IDC_DELAY1_RANDOM_S2            1037
#define IDC_TIME_E2                     1038
#define IDC_PREVIEW                     1039
#define IDC_DELAY2_S2                   1040
#define IDC_TIME_RANDOM_E2              1041
#define IDC_DELAY2_RANDOM_S2            1042
#define IDC_COUNT_RANDOM_E3             1043
#define IDC_COUNT_RANDOM_S3             1044
#define IDC_DELAY_E3                    1045
#define IDC_DELAY1_S3                   1046
#define IDC_DELAY_RANDOM_E3             1047
#define IDC_DELAY1_RANDOM_S3            1048
#define IDC_TIME_E3                     1049
#define IDC_DELAY2_S3                   1050
#define IDC_TIME_RANDOM_E3              1051
#define IDC_DELAY2_RANDOM_S3            1052
#define IDC_COUNT_RANDOM_E4             1053
#define IDC_COUNT_RANDOM_S4             1054
#define IDC_DELAY_E4                    1055
#define IDC_DELAY1_S4                   1056
#define IDC_DELAY_RANDOM_E4             1057
#define IDC_DELAY1_RANDOM_S4            1058
#define IDC_TIME_E4                     1059
#define IDC_DELAY2_S4                   1060
#define IDC_TIME_RANDOM_E4              1061
#define IDC_DELAY2_RANDOM_S4            1062
#define IDC_COUNT_RANDOM_E5             1063
#define IDC_COUNT_RANDOM_S5             1064
#define IDC_DELAY_E5                    1065
#define IDC_DELAY1_S5                   1066
#define IDC_DELAY_RANDOM_E5             1067
#define IDC_DELAY1_RANDOM_S5            1068
#define IDC_TIME_E5                     1069
#define IDC_DELAY2_S5                   1070
#define IDC_TIME_RANDOM_E5              1071
#define IDC_DELAY2_RANDOM_S5            1072
#define IDC_DIAGRAM_B2                  1073
#define IDC_DIAGRAM_B3                  1074
#define IDC_DIAGRAM_B4                  1075
#define IDC_DIAGRAM_B5                  1076
#define IDC_CLOSE                       1077
#define IDC_SNAPSHOT                    1077
#define IDC_DIAGRAM_B7                  1077
#define IDC_CLOSE_EFFECT_DIALOG         1078
#define IDC_DIAGRAM_B8                  1078
#define IDC_DIAGRAM_B9                  1079
#define IDC_DIAGRAM_B10                 1080
#define IDC_SLIDER1                     1087
#define IDC_INDEX0                      1088
#define IDC_INDEX_TEXT1                 1088
#define IDC_INDEX1                      1089
#define IDC_INDEX_TEXT2                 1089
#define IDC_INDEX2                      1090
#define IDC_INDEX_TEXT3                 1090
#define IDC_INDEX3                      1091
#define IDC_INDEX_TEXT4                 1091
#define IDC_INDEX4                      1092
#define IDC_INDEX_TEXT5                 1092
#define IDC_BASE_FILE                   1094
#define IDC_CURRENT_FILE                1095
#define IDC_IMAGE_COUNT                 1096
#define IDC_IMAGE0                      1097
#define IDC_IMAGE_BUTTON1               1097
#define IDC_IMAGE1                      1098
#define IDC_IMAGE_BUTTON2               1098
#define IDC_IMAGE2                      1099
#define IDC_IMAGE_BUTTON3               1099
#define IDC_IMAGE3                      1100
#define IDC_IMAGE_BUTTON4               1100
#define IDC_IMAGE4                      1101
#define IDC_IMAGE_BUTTON5               1101
#define IDC_IMPORT_IMAGE                1102
#define IDC_IMAGE_SIZE                  1103
#define ID_IMPORT_SINGLE                1103
#define ID_IMPORT_ALL                   1104
#define IDC_IMAGE_TYPE                  1104
#define IDC_IMPORT_IMAGE_SIZE           1105
#define IDC_EXPORT_IMAGE                1105
#define IDC_REPLACE_CHECK               1106
#define IDC_ANALYZE_COLORS              1106
#define IDC_REPLACE_IMAGE               1106
#define IDC_UPDATE_IMAGE                1107
#define IDC_IMPORT_IMAGE_COUNT          1108
#define IDC_IMPORT_FILE                 1109
#define IDC_IMPORT_WILDCARD_FILE        1110
#define IDC_FPS_EDIT                    1110
#define IDC_PART_FPS_EDIT               1110
#define IDC_FPS_RANDOM_E1               1111
#define IDC_FPS_RANDOM_EDIT             1111
#define IDC_GR_XSIZE_EDIT               1111
#define IDC_PART_FPS_RANDOM_EDIT        1111
#define IDC_FPS_SPINNER                 1112
#define IDC_PART_FPS_SPIN               1112
#define IDC_FPS_RANDOM_S1               1113
#define IDC_FPS_RANDOM_SPINNER          1113
#define IDC_GR_XSIZE_SPIN               1113
#define IDC_PART_FPS_RANDOM_SPIN        1113
#define IDC_GR_YSIZE_EDIT               1114
#define IDC_PART_LIFE_EDIT              1114
#define IDC_SWOOSH_EDGE_COLOR_EDIT      1114
#define IDC_PART_ZBIAS_EDIT             1114
#define IDC_GR_YSIZE_SPIN               1115
#define IDC_PART_LIFE_SPIN              1115
#define IDC_SWOOSH_EDGE_COLOR_SPIN      1115
#define IDC_PART_ZBIAS_SPIN             1115
#define IDC_GRAPHIC                     1116
#define IDC_GRAPHIC_COMBO               1116
#define IDC_PART_LEASH_EDIT             1116
#define IDC_PART_LIFE_RANDOM_EDIT       1117
#define IDC_SWOOSH_EDGE_ALPHA_EDIT      1117
#define IDC_IMAGE                       1118
#define IDC_PART_LIFE_RANDOM_SPIN       1118
#define IDC_SWOOSH_EDGE_ALPHA_SPIN      1118
#define IDC_CHECK1                      1119
#define IDC_FPS_RANDOM_CHECK            1119
#define IDC_GR_ASPECT_CHECK             1119
#define IDC_X_SIZE_HIDE                 1119
#define IDC_PART_FPS_RANDOM_CHECK       1119
#define IDC_BULLET_CHECK                1119
#define IDC_SOUND1                      1119
#define IDC_PART_COLLIDES               1119
#define IDC_EMIT_MIN_DIST_CHECK         1119
#define IDC_PART_LEASH_SPIN             1119
#define IDC_PIGGYBACK                   1119
#define IDC_SWOOSH_EMIT_SPARSE_CYLINDER_CHECK 1119
#define IDC_FPS_S1                      1120
#define IDC_FPS_RANDOM_CHECK2           1120
#define IDC_TIME_RANDOM_CHECK2          1120
#define IDC_Y_SIZE_HIDE                 1120
#define IDC_STANDARD_GRAVITY_CHECK      1120
#define IDC_PART_RANDOM_FRAME_CHECK     1120
#define IDC_EMIT_MOVE_ONLY_CHECK        1120
#define IDC_PART_LEASH_RANDOM_EDIT      1120
#define IDC_FPS_E1                      1121
#define IDC_FPS_RANDOM_CHECK3           1121
#define IDC_TIME_RANDOM_CHECK3          1121
#define IDC_RED_HIDE                    1121
#define IDC_PART_XSIZE_EDIT             1121
#define IDC_PART_LIGHTED_CHECK          1121
#define IDC_PART_LEASH_RANDOM_SPIN      1121
#define IDC_EMIT_SCALE_RANDOM_CHECK     1121
#define IDC_SWOOSH_LIFETIME_EDIT        1121
#define IDC_IMAGE_BUTTON                1122
#define IDC_GREEN_HIDE                  1122
#define IDC_PART_YSIZE_EDIT             1122
#define IDC_SOUND2                      1122
#define IDC_EMIT_DELAY_RANDOM_CHECK     1122
#define IDC_IMAGE_BUTTON6               1123
#define IDC_IMAGE_B2                    1123
#define IDC_IMAGE_XMIRROR_BUTTON        1123
#define IDC_BLUE_HIDE                   1123
#define IDC_PART_ORBIT_RADIUS_EDIT      1123
#define IDC_SWOOSH_LIFETIME_SPIN        1123
#define IDC_IMAGE_BUTTON7               1124
#define IDC_IMAGE_B3                    1124
#define IDC_IMAGE_YMIRROR_BUTTON        1124
#define IDC_ALPHA_HIDE                  1124
#define IDC_PART_ORBIT_ROTVEL_EDIT      1124
#define IDC_FPS_RANDOM_CHECK4           1125
#define IDC_IMAGE_XYMIRROR_BUTTON       1125
#define IDC_TIME_RANDOM_CHECK4          1125
#define IDC_PART_ORBIT_RADIUS_VEL_EDIT  1125
#define IDC_IMAGE_BUTTON8               1126
#define IDC_IMAGE_B4                    1126
#define IDC_PART_XSIZE_SPIN             1126
#define IDC_PART_NO_DISTORTION_CHECK    1126
#define IDC_SWOOSH_LOD_EDIT             1126
#define IDC_FPS_RANDOM_CHECK5           1127
#define IDC_TIME_RANDOM_CHECK5          1127
#define IDC_PART_YSIZE_SPIN             1127
#define IDC_PART_FORCEFIELD_CHECK       1127
#define IDC_SWOOSH_LOD_SPIN             1127
#define IDC_IMAGE_BUTTON9               1128
#define IDC_IMAGE_B5                    1128
#define IDC_PART_ZBUFFER_CHECK          1128
#define IDC_PART_ORBIT_RADIUS_SPIN      1128
#define IDC_IMAGE_B1                    1129
#define IDC_PART_ASPECT_CHECK           1129
#define IDC_PART_ADDITIVE_CHECK         1129
#define IDC_TIME_RANDOM_CHECK1          1130
#define IDC_PART_ORBIT_ROTVEL_SPIN      1130
#define IDC_PART_FLOATS_CHECK           1130
#define IDC_PART_YMIRROR_CHECK          1131
#define IDC_SOUND3                      1131
#define IDC_PART_ORBIT_RADIUS_VEL_SPIN  1131
#define IDC_PART_XMIRROR_CHECK          1132
#define IDC_SOUND4                      1132
#define IDC_SOUND5                      1133
#define IDC_PART_RANDOM_ASPECT_CHECK    1134
#define IDC_ORIENT_FREE_RADIO           1134
#define IDC_ORIENT_GROUND_RADIO         1135
#define IDC_ORIENT_WALL_RADIO           1136
#define IDC_ANIM_LOOP_RADIO             1137
#define IDC_GR_FPS_EDIT                 1137
#define IDC_ANIM_PING_PONG_RADIO        1138
#define IDC_GR_FPS_SPIN                 1138
#define IDC_ANIM_ONE_SHOT_RADIO         1139
#define IDC_PART_XSIZE_RANDOM_EDIT      1139
#define IDC_PART_YSIZE_RANDOM_EDIT      1140
#define IDC_ORIENT_SCREEN_RADIO2        1140
#define IDC_ORIENT_SCREEN_RADIO         1140
#define IDC_PART_ORBIT_RADIUS_RANDOM_EDIT 1141
#define IDC_PART_ORBIT_ROTVEL_RANDOM_EDIT 1142
#define IDC_PART_ORBIT_RADIUS_VEL_RANDOM_EDIT 1143
#define IDC_PART_XSIZE_RANDOM_SPIN      1146
#define IDC_PART_YSIZE_RANDOM_SPIN      1147
#define IDC_PART_ORBIT_RADIUS_RANDOM_SPIN 1148
#define IDC_PART_ORBIT_ROTVEL_RANDOM_SPIN 1149
#define IDC_PART_ORBIT_RADIUS_VEL_RANDOM_SPIN 1150
#define IDC_SPLINE                      1155
#define IDC_ADSR                        1156
#define IDC_STRAIGHT                    1157
#define IDC_FLAT                        1158
#define IDC_X_SIZE_ENVELOPE             1159
#define IDC_Y_SIZE_ENVELOPE             1160
#define IDC_RED_ENVELOPE                1161
#define IDC_GREEN_ENVELOPE              1162
#define IDC_BLUE_ENVELOPE               1163
#define IDC_ALPHA_ENVELOPE              1164
#define IDC_PART_POS_RAND_EDIT          1168
#define IDC_PART_POS_RAND_SPIN          1169
#define IDC_PART_XVEL_EDIT              1170
#define IDC_PART_XVEL_SPIN              1171
#define IDC_PART_YVEL_EDIT              1172
#define IDC_PART_YVEL_SPIN              1173
#define IDC_PART_ZVEL_EDIT              1174
#define IDC_PART_ZVEL_SPIN              1175
#define IDC_PART_GRAVITY_EDIT           1176
#define IDC_PART_GRAVITY_SPIN           1177
#define IDC_PART_ACCEL_EDIT             1178
#define IDC_PART_ACCEL_SPIN             1179
#define IDC_PART_VEL_RAND_EDIT          1180
#define IDC_PART_VEL_RAND_SPIN          1181
#define IDC_PART_VEL_CONE_EDIT          1182
#define IDC_PART_VEL_CONE_SPIN          1183
#define IDC_PART_XROT_EDIT              1184
#define IDC_PART_XROT_SPIN              1185
#define IDC_INIT_ROT_RAND_CHECK         1186
#define IDC_PART_XPOS_EDIT              1187
#define IDC_ALPHA_MASK_CHECK            1187
#define IDC_PART_XPOS_SPIN              1188
#define IDC_PART_YPOS_EDIT              1189
#define IDC_PREVIEW_RATE_SPIN           1189
#define IDC_PREVIEW_DELAY_SPIN          1189
#define IDC_PART_YROT_EDIT              1190
#define IDC_PREVIEW_RATE_EDIT           1190
#define IDC_PREVIEW_DELAY_EDIT          1190
#define IDC_PART_YROT_SPIN              1191
#define IDC_COLOR_PAIR                  1191
#define IDC_PREVIEW_MPH_EDIT            1191
#define IDC_PART_ZROT_EDIT              1192
#define IDC_COLOR_RGB                   1192
#define IDC_PREVIEW_MPH_SPIN            1192
#define IDC_PART_ZROT_SPIN              1193
#define IDC_COLOR1                      1193
#define IDC_PREVIEW_MODEL_XPOS_EDIT     1193
#define IDC_PART_ROT_RAND_EDIT          1194
#define IDC_COLOR2                      1194
#define IDC_PREVIEW_MODEL_XPOS_SPIN     1194
#define IDC_PART_ROT_RAND_SPIN          1195
#define IDC_PREVIEW_MODEL_YPOS_EDIT     1195
#define IDC_PART_ROT_ACCEL_EDIT         1196
#define IDC_PREVIEW_MODEL_YPOS_SPIN     1196
#define IDC_PART_ROT_ACCEL_SPIN         1197
#define IDC_BKG_COLOR                   1197
#define IDC_PART_YPOS_SPIN              1198
#define IDC_PREVIEW_MODEL_ZPOS_EDIT     1198
#define IDC_PART_ZPOS_EDIT              1199
#define IDC_CAMERA_POS                  1199
#define IDC_PART_ZPOS_SPIN              1200
#define IDC_CURRENT_CAMERA_POS          1200
#define IDC_COLLIDE_CONTINUE            1201
#define IDC_ROT_FOLLOW_VEL_CHECK        1201
#define IDC_PREVIEW_STOP                1201
#define IDC_COLLIDE_DIE                 1202
#define IDC_PART_VEL_CONE2_EDIT         1202
#define IDC_PREVIEW_RESET_EMITTER       1202
#define IDC_COLLIDE_STICK               1203
#define IDC_PART_VEL_CONE2_SPIN         1203
#define IDC_PREVIEW_RESET_ALL           1203
#define IDC_COLLIDE_BOUNCE              1204
#define IDC_PREVIEW_RESET_CAMERA        1204
#define IDC_PART_PREVIEW2               1204
#define IDC_RANDOM_POS_PLANE_CHECK      1204
#define IDC_COLLIDE_SPAWN               1205
#define IDC_PREVIEW_UPDATE_STAGE        1205
#define IDC_SPAWN_CONTINUE              1206
#define IDC_PREVIEW_UPDATE_EMITTER_MODEL 1206
#define IDC_SPAWN_DEFAULT               1207
#define IDC_PREVIEW_CLEAR_EMITTER_MODEL 1207
#define IDC_SPAWN_STICK                 1208
#define IDC_PREVIEW_MODEL_ZPOS_SPIN     1208
#define IDC_SPAWN_BOUNCE                1209
#define IDC_PREVIEW_MODEL_YROT_EDIT     1209
#define IDC_PREVIEW_MODEL_YROT_SPIN     1210
#define IDC_COLLIDE_BOUNCE_EDIT         1211
#define IDC_PREVIEW_YPOS_EDIT           1211
#define IDC_COLLIDE_BOUNCE_SPIN         1212
#define IDC_PREVIEW_YPOS_SPIN           1212
#define IDC_SPAWN_BOUNCE_EDIT           1213
#define IDC_WIND_MPH_EDIT               1213
#define IDC_SPAWN_BOUNCE_SPIN           1214
#define IDC_WIND_MPH_SPIN               1214
#define IDC_PREVIEW_UPDATE_EMITTER_MODEL2 1215
#define IDC_PREVIEW_EMITTER_VEL         1215
#define IDC_SPAWN_COMBO                 1216
#define IDC_EFFECT_COMBO                1217
#define IDC_SURFACE_COMBO               1217
#define IDC_EMIT_RATE_EDIT              1218
#define IDC_EMIT_DELAY_EDIT             1218
#define IDC_EMIT_RATE_SPIN              1219
#define IDC_EMIT_DELAY_SPIN             1219
#define IDC_EMIT_RATE_RANDOM_EDIT       1220
#define IDC_EMIT_DELAY_RANDOM_EDIT      1220
#define IDC_EMIT_RATE_RANDOM_SPIN       1221
#define IDC_EMIT_DELAY_RANDOM_SPIN      1221
#define IDC_EMIT_TYPE_COMBO             1222
#define IDC_EMIT_IMAGE_BUTTON           1223
#define IDC_EMIT_VEL_PCT_EDIT           1224
#define IDC_PREVIEW_FOLLOW_CHECK        1224
#define IDC_EMIT_VEL_PCT_SPIN           1225
#define IDC_PREVIEW_GRAVITY_CHECK       1225
#define IDC_PICK_COLOR1                 1225
#define IDC_EMIT_ADD_VEL_PCT_EDIT       1226
#define IDC_PICK_COLOR2                 1226
#define IDC_PREVIEW_20HZ_CHECK          1226
#define IDC_PREVIEW_PARTICLE_PATH       1226
#define IDC_EMIT_ADD_VEL_PCT_SPIN       1227
#define IDC_EMIT_MIN_DIST_EDIT          1228
#define IDC_PREVIEW_EMITTER_MODEL       1228
#define IDC_PROGRESS_BAR                1228
#define IDC_EMIT_MIN_DIST_SPIN          1229
#define IDC_PROGRESS_INFO               1229
#define IDC_EMIT_RADIUS_EDIT            1230
#define IDC_PROGRESS_FILE               1230
#define IDC_EMIT_RADIUS_SPIN            1231
#define IDC_CHANNEL1                    1231
#define IDC_EMIT_ANG_VEL_EDIT           1232
#define IDC_CHANNEL2                    1232
#define IDC_PREVIEW_PARTICLE            1232
#define IDC_EMIT_ANG_VEL_SPIN           1233
#define IDC_CHANNEL3                    1233
#define IDC_PART_LEASH_CHECK            1233
#define IDC_CHANNEL4                    1234
#define IDC_PART_NO_VIEW_CULL_CHECK     1234
#define IDC_EMIT_GO_RADIUS_EDIT         1234
#define IDC_CHANNEL5                    1235
#define IDC_EMIT_GO_RADIUS_SPIN         1235
#define IDC_EMIT_LIFE_SPIN              1236
#define IDC_CHANNEL6                    1236
#define IDC_EMIT_LIFE_EDIT              1237
#define IDC_CHANNEL7                    1237
#define IDC_EMIT_LIFE_RANDOM_SPIN       1238
#define IDC_CHANNEL8                    1238
#define IDC_EMIT_LIFE_RANDOM_EDIT       1239
#define IDC_CHANNEL9                    1239
#define IDC_SURFACE_LIST                1240
#define IDC_EMIT_SCALE_EDIT             1240
#define IDC_CHANNEL10                   1240
#define IDC_SURFACE_USE_DEFAULT         1241
#define IDC_EMIT_SCALE_SPIN             1241
#define IDC_SURFACE_LIST_COMBO          1242
#define IDC_EMIT_SCALE_RANDOM_EDIT      1242
#define IDC_ADD_SURFACE                 1243
#define IDC_EMIT_SCALE_RANDOM_SPIN      1243
#define IDC_DELETE_SURFACE              1244
#define IDC_EMIT_LOD1_RADIUS_EDIT       1244
#define IDC_SURFACE_NAME_EDIT           1245
#define IDC_EMIT_LOD1_RADIUS_SPIN       1245
#define IDC_EMIT_LOD2_RADIUS_EDIT       1246
#define IDC_EMIT_LOD2_RADIUS_SPIN       1247
#define IDC_PREVIEW_SURFACE_COMBO       1248
#define IDC_EMIT_FLUX_SIZE_EDIT         1248
#define IDC_EMITTER                     1249
#define IDC_PREVIEW_TIMER_COMBO         1249
#define IDC_EMIT_FLUX_SIZE_SPIN         1249
#define IDC_EMITTER_BUTTON              1250
#define IDC_EJECT_PARTICLE_RADIO        1251
#define IDC_EJECT_DEFAULT_RADIO         1252
#define IDC_EMIT_NEAR_DISTANCE_EDIT     1252
#define IDC_COLLIDE_STOP_ROTATING       1253
#define IDC_EMIT_NEAR_DISTANCE_SPIN     1253
#define IDC_COLLIDE_STOP_ANIMATING      1254
#define IDC_ORBIT_PLANE_SCREEN          1254
#define IDC_EMIT_INVIS_DISTANCE_EDIT    1254
#define IDC_ORBIT_PLANE_GROUND          1255
#define IDC_EMIT_INVIS_DISTANCE_SPIN    1255
#define IDC_COLLIDE_CREATE_WATER_SPRITE 1255
#define IDC_ORBIT_PLANE_ALIGN_TO_VEL    1256
#define IDC_EMIT_FAR_SCALE_EDIT         1256
#define IDC_ORBIT_INIT_ROT_RAND_CHECK   1257
#define IDC_EMIT_FAR_SCALE_SPIN         1257
#define IDC_SWOOSH_COMBO                1258
#define IDC_EMIT_NEAR_SCALE_EDIT        1258
#define IDC_SWOOSH_EMIT_TYPE_COMBO      1259
#define IDC_EMIT_NEAR_SCALE_SPIN        1259
#define IDC_SWOOSH_EMIT_IMAGE_BUTTON    1260
#define IDC_EMIT_FAR_DISTANCE_EDIT      1260
#define IDC_SWOOSH_EMIT_RADIUS_EDIT     1261
#define IDC_EMIT_FAR_DISTANCE_SPINx     1261
#define IDC_SWOOSH_EMIT_RADIUS_SPIN     1262
#define IDC_SWOOSH_EMIT_HEIGHT_EDIT     1263
#define IDC_PART_COLLIDES_WORLD         1263
#define IDC_SWOOSH_EMIT_HEIGHT_SPIN     1264
#define IDC_PART_COLLIDES_ACTORS        1264
#define IDC_ALIGN_TO_VEL_CHECK          1264
#define IDC_SWOOSH_EMIT_YVEL_EDIT       1265
#define IDC_PART_COLLIDES_WATER         1265
#define IDC_PERPENDICULAR_CHECK         1265
#define IDC_SWOOSH_EMIT_YVEL_SPIN       1266
#define IDC_SWOOSH_EMIT_ROTVEL_EDIT     1267
#define IDC_SWOOSH_EMIT_ROTVEL_SPIN     1268
#define IDC_SWOOSH_EMIT_POINTS_EDIT     1269
#define IDC_SWOOSH_EMIT_POINTS_SPIN     1270
#define IDC_SWOOSH_EMIT_ANGLE_EDIT      1271
#define IDC_SWOOSH_EMIT_ANGLE_SPIN      1272
#define IDC_SWOOSH_EMIT_TIME_EDIT       1273
#define IDC_SWOOSH_EMIT_TIME_SPIN       1274
#define IDC_SWOOSH_EMIT_WIDTH_EDIT      1275
#define IDC_SWOOSH_EMIT_WIDTH_SPIN      1276
#define IDC_SWOOSH_EMIT_RADIUS_RANDOM_PCT_EDIT 1277
#define IDC_SWOOSH_EMIT_RADIUS_RANDOM_PCT_SPIN 1278
#define IDC_SWOOSH_EMIT_WIDTH_RANDOM_PCT_EDIT 1279
#define IDC_SWOOSH_EMIT_WIDTH_RANDOM_PCT_SPIN 1280
#define IDC_SWOOSH_EMIT_YVEL_RANDOM_PCT_EDIT 1281
#define IDC_SWOOSH_EMIT_YVEL_RANDOM_PCT_SPIN 1282
#define IDC_SWOOSH_EMIT_LIFE_EDIT       1283
#define IDC_SWOOSH_EMIT_LIFE_SPIN       1284
#define IDC_SWOOSH_EMIT_LIFE_RANDOM_PCT_EDIT 1285
#define IDC_SWOOSH_EMIT_LIFE_RANDOM_PCT_SPIN 1286
#define IDC_PART_PREVIEW                1300
#define ID_NEW_EFFECT                   32771
#define ID_RENAME                       32773
#define ID_EFFECT_DIALOG                32774
#define ID_MOVE_TO_TOP                  32775
#define ID_DELETE                       32776
#define ID_MOVE_TO_BOTTOM               32777
#define ID_NEW_ELEMENT                  32778
#define ID_NEW_PARTICLE                 32778
#define ID_ELEMENT_DIALOG               32779
#define ID_PARTICLE_DIALOG              32779
#define ID_VIEW_ELEMENTS                32780
#define ID_VIEW_EFFECTS                 32781
#define ID_VIEW_GRAPHICS                32782
#define ID_NEW_GRAPHIC                  32783
#define ID_GRAPHIC_DIALOG               32784
#define ID_IMPORTIMAGE                  32785
#define ID_MARK_ICON                    32787
#define ID_MOVE_LEFT                    32788
#define ID_MOVE_RIGHT                   32789
#define IDC_COPY_CHANNEL1               32790
#define IDC_COPY_CHANNEL                32790
#define IDC_COPY_CHANNEL2               32791
#define IDC_COPY_CHANNEL3               32792
#define IDC_COPY_CHANNEL4               32793
#define IDC_COPY_CHANNEL5               32794
#define IDC_PASTE_CHANNEL1              32795
#define IDC_PASTE_CHANNEL               32795
#define IDC_PASTE_CHANNEL2              32796
#define IDC_PASTE_CHANNEL3              32797
#define IDC_PASTE_CHANNEL4              32798
#define IDC_PASTE_CHANNEL5              32799
#define ID_FILE_EXPORT                  32800
#define ID_FILE_ANALYZE                 32801
#define ID_DELETE_ALL                   32802
#define ID_ENVELOPE_DIALOG              32803
#define ID_VIEW_PARTICLES               32804
#define IDC_CLEAR_CHANNEL1              32805
#define IDC_CLEAR_CHANNEL               32805
#define IDC_CLEAR_CHANNEL2              32806
#define IDC_CLEAR_CHANNEL3              32807
#define IDC_CLEAR_CHANNEL4              32808
#define IDC_CLEAR_CHANNEL5              32809
#define ID_VIEW_SFX                     32810
#define ID_VIEW_EXPORT_LOG              32811
#define ID_FILE_MERGE                   32812
#define ID_VIEW_EMITTERS                32813
#define ID_NEW_EMITTER                  32814
#define ID_EMITTER_DIALOG               32815
#define ID_TEXTURE_ANALYZE              32816
#define ID_PREVIEW                      32817
#define ID_FILE_EXPORT_GCN              32818
#define ID_VIEW_SWOOSHES                32819
#define ID_NEW_SWOOSH                   32820
#define ID_SWOOSH_DIALOG                32821
#define ID_FILE_EXPORT_PS2              32822
#define ID_FILE_EXPORT_PC               32823
#define ID_VIEW_SWOOSH_EMITTERS         32824
#define ID_NEW_SWOOSH_EMITTER           32825
#define ID_SWOOSH_EMITTER_DIALOG        32826
#define ID_PREVIEW_CLEARSTAGE           32827
#define ID_PREVIEW_CLEAREMITTERMODEL    32828
#define ID_REPAIR_CLEARSTAGE            32829
#define ID_REPAIR_CLEAREMITTERMODEL     32830
#define ID_VIEW_CLOSE                   32831
#define ID_CLOSE_ALLBUTEFFECTS          32832
#define ID_CLOSE_ALLBUTPARTICLES        32833
#define ID_CLOSE_ALLBUTGRAPHICS         32834
#define ID_CLOSE_ALLBUTEMITTERS         32835
#define ID_CLOSE_ALLBUTSWOOSHES         32836
#define ID_CLOSE_ALLBUTSWOOSHEMITTERS   32837
#define ID_FINDASSOCIATES               32844
#define ID_FILE_SETASSOCIATELOGFILE     32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1266
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
