//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AssetManager.rc
//
#define ID_MANIFEST                     1
#define ID_NEW_DATABASE                 3
#define ID_EDIT_DATABASE                4
#define ID_DELETE_DATABASE              5
#define ID_ACCEPT_DATABASE              6
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ASSETMANAGER_DIALOG         102
#define IDS_FOLDER_SETS_SORT            102
#define IDS_BUTTON_FOLDER_SETS_SORT     102
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAINAPP                129
#define IDR_TOOLBAR                     132
#define IDR_TOOLBAR_MAIN                132
#define IDB_BITMAP_TEST                 134
#define IDB_BITMAP_BROWSE               135
#define IDD_OPTIONS                     137
#define IDD_DEFAULT_AUTO_FREEZE_OPTIONS 137
#define IDB_TREENORMAL                  139
#define IDD_LOADDB_DIALOG               141
#define IDD_SYNC_DIALOG                 142
#define IDR_MENU_INDICATOR              143
#define IDB_SYNC                        145
#define IDB_COPYTOLEFT                  146
#define IDB_COPYTORIGHT                 147
#define IDB_DELETELEFT                  148
#define IDB_DELETERIGHT                 149
#define IDB_SYNC_DISABLED               151
#define IDB_COPYTOLEFT_DISABLED         152
#define IDB_COPYTORIGHT_DISABLED        153
#define IDB_DELETELEFT_DISABLED         154
#define IDB_DELETERIGHT_DISABLED        155
#define IDB_BTTN_REFRESH                156
#define IDB_BTTN_VIEW_ALL               157
#define IDB_BTTN_VIEW_CPY_LEFT          158
#define IDB_BTTN_VIEW_CPY_RIGHT         159
#define IDB_BTTN_VIEW_DLT_BOTH          160
#define IDB_BTTN_VIEW_DLT_LEFT          161
#define IDB_BTTN_VIEW_DLT_RIGHT         162
#define IDB_BTTN_VIEW_EQUAL             163
#define IDB_BTTN_VIEW_NEWER_LEFT        164
#define IDB_BTTN_VIEW_NEWER_RIGHT       165
#define IDB_BTTN_VIEW_NO_ACTION         166
#define IDB_BTTN_VIEW_ORPHAN_LEFT       167
#define IDB_BTTN_VIEW_ORPHAN_RIGHT      168
#define IDD_SYNC_CONFIRM                169
#define IDB_BTTN_VIEW_EXCLUDED          170
#define IDB_BTTN_VIEW_FROZEN            172
#define IDR_MANIFEST                    173
#define IDB_LOCK                        176
#define IDB_BTTN_VIEW_FROZEN_DISABLED   177
#define IDB_BTTN_VIEW_EXCLUDED_DISABLED 178
#define IDD_OPEN_DATABASE               179
#define IDI_BROWSE                      180
#define IDD_UPDATE_DUPLICATES           181
#define IDB_UPDATE_DUPLICATES           182
#define IDR_MAIN                        183
#define IDD_UPDATE_DUPLICATES_OPTIONS   185
#define IDD_FOLDER_SET_AUTO_FREEZE_OPTIONS 186
#define IDD_AUTO_FREEZE_LIST            187
#define IDR_SYNC_STYLE_PATTERN01        188
#define IDR_SYNC_STYLE_PATTERN01T       189
#define IDR_SYNC_STYLE_PATTERN02        190
#define IDR_SYNC_STYLE_PATTERN02T       191
#define IDR_SYNC_STYLE_PATTERN03        192
#define IDR_SYNC_STYLE_PATTERN03T       193
#define IDR_SYNC_STYLE_PATTERN04        194
#define IDR_SYNC_STYLE_PATTERN04T       195
#define IDR_SYNC_STYLE_PATTERN05        196
#define IDR_SYNC_STYLE_PATTERN05T       197
#define IDR_SYNC_STYLE_PATTERN06        198
#define IDR_SYNC_STYLE_PATTERN06T       199
#define IDR_SYNC_STYLE_PATTERN07        200
#define IDR_SYNC_STYLE_PATTERN07T       201
#define IDR_SYNC_STYLE_PATTERN08        202
#define IDR_SYNC_STYLE_PATTERN08T       203
#define IDR_SYNC_STYLE_PATTERN09        204
#define IDR_SYNC_STYLE_PATTERN09T       205
#define IDR_SYNC_STYLE_PATTERN10        206
#define IDR_SYNC_STYLE_PATTERN10T       207
#define IDR_SYNC_STYLE_PATTERN11        208
#define IDR_SYNC_STYLE_PATTERN11T       209
#define IDR_UPDATE_DUPLICATES           210
#define IDD_COMPARISON_METHOD           211
#define IDD_SCAN_SETTINGS               211
#define IDR_TREE_INDICATOR              215
#define IDD_SYNC_SETTINGS               217
#define IDI_SORT                        221
#define IDC_COMBO_LEFT                  1002
#define IDC_TREE_LEFT                   1003
#define IDC_TREE_RIGHT                  1004
#define IDC_TREE_SYNC_INDICATORS        1005
#define IDC_COMBO_RIGHT                 1006
#define IDC_COMBO_NAMES                 1007
#define IDC_STATIC_NAMES                1008
#define IDC_FOLDER_SETS_TITLE           1008
#define IDC_STATIC_LEFT_FOLDER          1009
#define IDC_SYNC_STYLE_TITLE            1009
#define IDC_STATIC_RIGHT_FOLDER         1010
#define IDC_BUTTON_LEFT_BROWSE          1011
#define IDC_BUTTON_RIGHT_BROWSE         1012
#define IDC_LOADDB_TEXT1                1013
#define IDC_LOADDB_TEXT2                1014
#define IDC_LOADDB_TEXT3                1015
#define IDB_CANCEL                      1016
#define IDC_SYNC_TEXT1A                 1017
#define IDC_SYNC_TEXT2A                 1018
#define IDC_SYNC_TEXT1B                 1019
#define IDC_SYNC_TEXT2B                 1020
#define IDC_PROGRESS1                   1021
#define IDC_PROGRESS2                   1022
#define IDC_SYNC_TEXT3                  1023
#define IDC_SYNC_TEXT4                  1024
#define IDC_SYNC_TEXT5                  1025
#define IDC_LOGWINDOW                   1027
#define IDC_CHECK1                      1028
#define IDB_DONE                        1029
#define IDC_CHECK2                      1029
#define IDC_LEFT_STATS_TEXT1            1030
#define IDC_EXIT_CHECK                  1030
#define IDC_CHECK3                      1030
#define IDC_RIGHT_STATS_TEXT1           1031
#define IDC_CHECK4                      1031
#define IDC_LEFT_STATS_TEXT3            1032
#define IDC_RIGHT_STATS_TEXT3           1033
#define IDC_SYNCBUTTON                  1034
#define IDC_LEFT_STATS_TEXT2            1035
#define IDC_RIGHT_STATS_TEXT2           1036
#define IDC_LEFT_STATS_TEXT4            1037
#define IDC_RIGHT_STATS_TEXT4           1038
#define IDC_LR_COPY_BUTTON              1039
#define IDC_L_DELETE                    1040
#define IDC_RL_COPY_BUTTON              1041
#define IDC_R_DELETE                    1042
#define IDC_BUTTON1                     1043
#define IDC_BTTN_VIEW_CPY_LEFT          1043
#define IDC_BTTN_VIEW_CPY_RIGHT         1044
#define IDC_CONFIRM1                    1044
#define IDC_BTTN_VIEW_DLT_LEFT          1045
#define IDC_CONFIRM2                    1045
#define IDC_FILE_PREFIXES               1045
#define IDC_BTTN_VIEW_DLT_RIGHT         1046
#define IDC_CONFIRM3                    1046
#define IDC_STATIC_VERSION              1046
#define IDC_BUTTON2                     1046
#define IDC_BTTN_VIEW_DLT_BOTH          1047
#define IDC_CONFIRM4                    1047
#define IDC_FILE_EXTENSIONS             1047
#define IDC_STATIC_DATE                 1047
#define IDC_BTTN_VIEW_NO_ACTION         1048
#define IDC_FOLDER_PREFIXES             1048
#define IDC_BTTN_VIEW_FROZEN            1048
#define IDC_BTTN_VIEW_NEWER_LEFT        1049
#define IDC_BUTTON3                     1049
#define IDC_BTTN_VIEW_NEWER_RIGHT       1050
#define IDC_BTTN_VIEW_ORPHAN_LEFT       1051
#define IDC_BTTN_VIEW_ORPHAN_RIGHT      1052
#define IDC_BTTN_VIEW_EQUAL             1053
#define IDC_BTTN_VIEW_ALL               1054
#define IDC_BTTN_REFRESH                1055
#define IDC_BTTN_VIEW_EXCLUDED          1056
#define IDC_LOCK_EXCLUDED               1057
#define IDC_LOCK_FROZEN                 1058
#define IDC_LOCK_EXCLUDED_BITMAP        1059
#define IDC_FOLDER_SETS                 1060
#define IDC_LOCK_FROZEN_BITMAP          1061
#define IDC_DATABASE_NAME               1061
#define ID_OK_BUTTON                    1062
#define ID_CANCEL_BUTTON                1063
#define IDC_DATABASE_DESCRIPTION        1064
#define IDC_FOLDER_PATH_LEFT            1064
#define IDC_FOLDER_PATH_RIGHT           1065
#define IDC_BUTTON_FOLDER_SETS_BROWSE   1066
#define IDC_BUTTON_FOLDER_SETS_SORT     1067
#define IDC_DUP_TREE                    1068
#define IDC_DUP_TEXT_1                  1069
#define IDC_DUP_TEXT_2                  1070
#define ID_UPDATE                       1071
#define IDC_INCLUDE_PARENT_DIRECTORY    1073
#define IDC_INCLUDE_FROZEN_DUPLICATES   1074
#define IDC_SYNC_STYLE                  1074
#define IDC_TEXT1                       1076
#define IDC_TEXT2                       1077
#define IDC_TEXT3                       1078
#define IDC_BUTTON4                     1080
#define IDC_LIST1                       1081
#define IDC_FRAME1                      1084
#define IDC_COMBO1                      1085
#define IDC_CLOSE_CHECK                 1086
#define IDC_STATUSBAR                   32500
#define ID_OPTIONS                      32771
#define ID_DEFAULT_OPTIONS              32771
#define ID_BUTTON_COMPARE               32772
#define ID_BUTTON_SYNC                  32773
#define ID_BUTTON_SHOW_UPDATETOLEFT     32776
#define ID_BUTTON_SHOW_ALL              32778
#define ID_BUTTON_SHOW_UPDATETORIGHT    32779
#define ID_BUTTON_SHOW_DELETEFROMLEFT   32780
#define ID_BUTTON_SHOW_DELETEFROMRIGHT  32781
#define ID_COPY_TO_LEFT                 32782
#define ID_COPY_TO_RIGHT                32783
#define ID_DELETE_FROM_LEFT             32784
#define ID_DELETE_FROM_RIGHT            32785
#define ID_DELETE_FROM_BOTH             32788
#define ID_SELECT_ALL                   32790
#define ID_SELECT_NONE                  32791
#define ID_INVERT_SELECTION             32792
#define ID_EXCLUDE                      32793
#define ID_UNFREEZE                     32794
#define ID_SET_DEFAULT                  32795
#define ID_EXPAND_ALL                   32796
#define ID_COLLAPSE_ALL                 32797
#define ID_UNFREEZE_ONLY                32798
#define ID_FREEZE                       32799
#define ID_FOLDER_SETS                  32800
#define ID_ADD_PREFIX                   32801
#define ID_REMOVE_PREFIX                32802
#define ID_RENAME                       32803
#define ID_SOURCE_FILE                  32804
#define ID_DEST_FILE                    32805
#define ID_DELETE_FILE                  32806
#define ID_UPDATE_DUPLICATES            32807
#define ID_ABOUT                        32808
#define ID_AUTO_FREEZE_ADD              32809
#define ID_AUTO_FREEZE_REMOVE           32810
#define ID_AUTO_FREEZE_REMOVE_INCLUDE_CHILDREN 32811
#define ID_HELP_CONTENTS                32812
#define ID_FOLDER_SET_OPTIONS           32813
#define ID_EXPLORE                      32819
#define IDS_SPECIFY_LEFT_FOLDER         57666
#define IDS_SPECIFY_RIGHT_FOLDER        57667
#define IDS_FOLDER_DOESNT_EXIST         57668
#define IDS_LEFT_FOLDER_DOESNT_EXIST    57668
#define IDS_PICK_ANOTHER                57669
#define IDS_FOLDER_DOESNT_EXIST_LEFT    57670
#define IDS_FOLDER_DOESNT_EXIST_RIGHT   57671
#define IDS_PICK_FOLDERS                57672
#define IDS_NAME_CANNOT_BE_EMPTY        57673
#define IDS_NAME_NEEDS_TO_BE_UNIQUE     57674
#define IDS_RIGHT_FOLDER_DOESNT_EXIST   57675
#define IDS_FOLDER_RENAME_ERROR         57676
#define IDS_FILE_RENAME_ERROR           57677
#define IDS_FOLDER_ADD_PREFIX_ERROR     57678
#define IDS_FILE_ADD_PREFIX_ERROR       57679
#define IDS_FOLDER_REMOVE_PREFIX_ERROR  57680
#define IDS_FILE_REMOVE_PREFIX_ERROR    57681
#define IDS_TIP_FILE                    57683
#define IDS_TIP_FOLDER                  57685
#define IDS_CANNOT_PICK_FOLDER_SET      57686
#define IDS_FOLDER_DOESNT_EXIST_BOTH    57687
#define IDS_TIP_FILE_SYNC               57688

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
