//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TupPlugin.rc
//
#define IDD_EXPORTDBLOPTIONS_DIALOG     9
#define IDC_FILTERCHAINPATHNAME         1000
#define IDD_EXPORTTUPOPTIONS_DIALOG     1001
#define IDD_EXPORTTUPSCENEOPTIONS_DIALOG 1001
#define IDC_PROCESSFILENAME             1001
#define IDD_IMPORTTUPOPTIONS_DIALOG     1002
#define IDB_EXPORTDBL                   1002
#define IDD_IMPORTTUPSCENEOPTIONS_DIALOG 1002
#define IDC_BROWSE_BUTTON               1002
#define IDC_BROWSE2_BUTTON              1003
#define IDD_EXPORTTUPMOTIONOPTIONS_DIALOG1 1003
#define IDD_EXPORTTUPMOTIONOPTIONS_DIALOG 1003
#define IDC_PROCESSFILESTATIC           1004
#define IDD_EXPORTTUPMOTIONOPTIONS_DIALOG2 1004
#define IDD_EXPORTMSETOPTIONS_DIALOG    1004
#define IDC_FILTERCHAINSTATIC           1005
#define IDC_EXPORTBINARY_CHECK          1007
#define IDC_EXPORTBINARY_CHECKBOX       1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1003
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
