// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosAccountPrivateDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosAccountPrivate) & DDLCLASS(EidosAccountPrivate)::operator=(const DDLCLASS(EidosAccountPrivate) &oOther){
    m_flags = oOther.m_flags;
    m_postalCode = oOther.m_postalCode;
    m_dateOfBirth = oOther.m_dateOfBirth;
    return *this;
}

qBool DDLCLASS(EidosAccountPrivate)::operator==(const DDLCLASS(EidosAccountPrivate) &oOther) const {
    if (!(m_flags == oOther.m_flags)) {return false;}
    if (!(m_postalCode == oOther.m_postalCode)) {return false;}
    if (!(m_dateOfBirth == oOther.m_dateOfBirth)) {return false;}
    return true;
}

void DDLCLASS(EidosAccountPrivate)::Add(Message *pMessageToSend, const DDLCLASS(EidosAccountPrivate) &oValue) {
    Data::Add(pMessageToSend,oValue);
    DDLTYPE(byte)::Add(pMessageToSend, oValue.m_flags);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_postalCode);
    DDLTYPE(datetime)::Add(pMessageToSend, oValue.m_dateOfBirth);
};

void DDLCLASS(EidosAccountPrivate)::Extract(Message *pReceivedMessage, DDLCLASS(EidosAccountPrivate) *pValue) {
    Data::Extract(pReceivedMessage,pValue);
    DDLTYPE(byte)::Extract(pReceivedMessage, &pValue->m_flags);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_postalCode);
    DDLTYPE(datetime)::Extract(pReceivedMessage, &pValue->m_dateOfBirth);
};

_PR_dataclass_methods_derived_impl(EidosAccountPrivate,Data);
END_NAMESPACE_QUAZAL;
