// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosAlertsDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosAlerts) & DDLCLASS(EidosAlerts)::operator=(const DDLCLASS(EidosAlerts) &oOther){
    m_friendInvitations = oOther.m_friendInvitations;
    m_clanInvitations = oOther.m_clanInvitations;
    m_matchInvitations = oOther.m_matchInvitations;
    return *this;
}

qBool DDLCLASS(EidosAlerts)::operator==(const DDLCLASS(EidosAlerts) &oOther) const {
    if (!(m_friendInvitations == oOther.m_friendInvitations)) {return false;}
    if (!(m_clanInvitations == oOther.m_clanInvitations)) {return false;}
    if (!(m_matchInvitations == oOther.m_matchInvitations)) {return false;}
    return true;
}

void DDLCLASS(EidosAlerts)::Add(Message *pMessageToSend, const DDLCLASS(EidosAlerts) &oValue) {
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Add(pMessageToSend, oValue.m_friendInvitations);
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Add(pMessageToSend, oValue.m_clanInvitations);
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Add(pMessageToSend, oValue.m_matchInvitations);
};

void DDLCLASS(EidosAlerts)::Extract(Message *pReceivedMessage, DDLCLASS(EidosAlerts) *pValue) {
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Extract(pReceivedMessage, &pValue->m_friendInvitations);
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Extract(pReceivedMessage, &pValue->m_clanInvitations);
    DDLTYPE(std_list)< DDLTYPE(uint32) >::Extract(pReceivedMessage, &pValue->m_matchInvitations);
};

END_NAMESPACE_QUAZAL;
