// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosAlertsDDL_H_
#define _EidosAlertsDDL_H_

#include <NetZ.h>
#include "Extensions/STL/STLExtTypes.h"
#include "Extensions/STL/STLExtTypes.h"
#include "Extensions/STL/STLExtTypes.h"

BEGIN_NAMESPACE_QUAZAL;
class EidosAlerts;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosAlerts): public RootObject {
public:
    DDLCLASS(EidosAlerts)() {};
    DDLCLASS(EidosAlerts)(const DDLCLASS(EidosAlerts) &oOther):
        m_friendInvitations(oOther.m_friendInvitations),
        m_clanInvitations(oOther.m_clanInvitations),
        m_matchInvitations(oOther.m_matchInvitations)
    {
    }
    virtual ~DDLCLASS(EidosAlerts)() {};
    const DDLCLASS(EidosAlerts) &operator=(const DDLCLASS(EidosAlerts) &oOther);
    qBool operator==(const DDLCLASS(EidosAlerts) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosAlerts) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosAlerts) *pValue);
    DDLTYPE(std_list)< DDLTYPE(uint32) >::CPPType m_friendInvitations;
    DDLTYPE(std_list)< DDLTYPE(uint32) >::CPPType m_clanInvitations;
    DDLTYPE(std_list)< DDLTYPE(uint32) >::CPPType m_matchInvitations;
    public:
    protected:
};


class DDLTYPE(EidosAlerts): public DDLType {
public:
    typedef EidosAlerts CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosAlerts)& oEidosAlerts) {
        DDLCLASS(EidosAlerts)::Add(pMessageToSend,oEidosAlerts);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosAlerts)* pEidosAlertsToRefresh) {
        DDLCLASS(EidosAlerts)::Extract(pReceivedMessage,pEidosAlertsToRefresh);
    }
};

class EidosAlerts: public DDLCLASS(EidosAlerts) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosAlertsDDL.h_H_
