// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosFriendDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosFriend) & DDLCLASS(EidosFriend)::operator=(const DDLCLASS(EidosFriend) &oOther){
    m_friendData = oOther.m_friendData;
    m_strClanAbbr = oOther.m_strClanAbbr;
    m_lstGatherings = oOther.m_lstGatherings;
    m_isLookingToPlay = oOther.m_isLookingToPlay;
    return *this;
}

qBool DDLCLASS(EidosFriend)::operator==(const DDLCLASS(EidosFriend) &oOther) const {
    if (!(m_friendData == oOther.m_friendData)) {return false;}
    if (!(m_strClanAbbr == oOther.m_strClanAbbr)) {return false;}
    if (!(m_lstGatherings == oOther.m_lstGatherings)) {return false;}
    if (!(m_isLookingToPlay == oOther.m_isLookingToPlay)) {return false;}
    return true;
}

void DDLCLASS(EidosFriend)::Add(Message *pMessageToSend, const DDLCLASS(EidosFriend) &oValue) {
    CLASSMETATYPE(FriendData)::Add(pMessageToSend, oValue.m_friendData);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_strClanAbbr);
    DDLTYPE(std_list)< DDLTYPE(any)< CLASSMETATYPE(Gathering), DDLTYPE(string) > >::Add(pMessageToSend, oValue.m_lstGatherings);
    DDLTYPE(bool)::Add(pMessageToSend, oValue.m_isLookingToPlay);
};

void DDLCLASS(EidosFriend)::Extract(Message *pReceivedMessage, DDLCLASS(EidosFriend) *pValue) {
    CLASSMETATYPE(FriendData)::Extract(pReceivedMessage, &pValue->m_friendData);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_strClanAbbr);
    DDLTYPE(std_list)< DDLTYPE(any)< CLASSMETATYPE(Gathering), DDLTYPE(string) > >::Extract(pReceivedMessage, &pValue->m_lstGatherings);
    DDLTYPE(bool)::Extract(pReceivedMessage, &pValue->m_isLookingToPlay);
};

END_NAMESPACE_QUAZAL;
