// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosClanInviteDDL_H_
#define _EidosClanInviteDDL_H_

#include <NetZ.h>

BEGIN_NAMESPACE_QUAZAL;
class EidosClanInvite;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosClanInvite): public RootObject {
public:
    DDLCLASS(EidosClanInvite)() {};
    DDLCLASS(EidosClanInvite)(const DDLCLASS(EidosClanInvite) &oOther):
        m_InviterClanID(oOther.m_InviterClanID),
        m_InviterClanAbbr(oOther.m_InviterClanAbbr),
        m_InviterClanName(oOther.m_InviterClanName),
        m_InviterPlayer(oOther.m_InviterPlayer),
        m_InviterClanRank(oOther.m_InviterClanRank),
        m_InviterClanMembers(oOther.m_InviterClanMembers),
        m_InviteePlayer(oOther.m_InviteePlayer),
        m_IsNew(oOther.m_IsNew)
    {
    }
    virtual ~DDLCLASS(EidosClanInvite)() {};
    const DDLCLASS(EidosClanInvite) &operator=(const DDLCLASS(EidosClanInvite) &oOther);
    qBool operator==(const DDLCLASS(EidosClanInvite) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosClanInvite) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosClanInvite) *pValue);
    DDLTYPE(uint32)::CPPType m_InviterClanID;
    DDLTYPE(string)::CPPType m_InviterClanAbbr;
    DDLTYPE(string)::CPPType m_InviterClanName;
    DDLTYPE(string)::CPPType m_InviterPlayer;
    DDLTYPE(int32)::CPPType m_InviterClanRank;
    DDLTYPE(uint32)::CPPType m_InviterClanMembers;
    DDLTYPE(string)::CPPType m_InviteePlayer;
    DDLTYPE(bool)::CPPType m_IsNew;
    public:
    protected:
};


class DDLTYPE(EidosClanInvite): public DDLType {
public:
    typedef EidosClanInvite CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosClanInvite)& oEidosClanInvite) {
        DDLCLASS(EidosClanInvite)::Add(pMessageToSend,oEidosClanInvite);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosClanInvite)* pEidosClanInviteToRefresh) {
        DDLCLASS(EidosClanInvite)::Extract(pReceivedMessage,pEidosClanInviteToRefresh);
    }
};

class EidosClanInvite: public DDLCLASS(EidosClanInvite) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosClanInviteDDL.h_H_
