// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosClanNoticeDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosClanNotice) & DDLCLASS(EidosClanNotice)::operator=(const DDLCLASS(EidosClanNotice) &oOther){
    m_From = oOther.m_From;
    m_Body = oOther.m_Body;
    return *this;
}

qBool DDLCLASS(EidosClanNotice)::operator==(const DDLCLASS(EidosClanNotice) &oOther) const {
    if (!(m_From == oOther.m_From)) {return false;}
    if (!(m_Body == oOther.m_Body)) {return false;}
    return true;
}

void DDLCLASS(EidosClanNotice)::Add(Message *pMessageToSend, const DDLCLASS(EidosClanNotice) &oValue) {
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_From);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_Body);
};

void DDLCLASS(EidosClanNotice)::Extract(Message *pReceivedMessage, DDLCLASS(EidosClanNotice) *pValue) {
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_From);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_Body);
};

END_NAMESPACE_QUAZAL;
