// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosFriendDDL_H_
#define _EidosFriendDDL_H_

#include <NetZ.h>
#include "Services/Friends/Protocol/FriendData.h"
#include "Extensions/STL/STLExtTypes.h"
#include "Extensions/Any/AnyExtTypes.h"
#include "Services/MatchMaking/Protocol/Gathering.h"

BEGIN_NAMESPACE_QUAZAL;
class EidosFriend;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosFriend): public RootObject {
public:
    DDLCLASS(EidosFriend)() {};
    DDLCLASS(EidosFriend)(const DDLCLASS(EidosFriend) &oOther):
        m_friendData(oOther.m_friendData),
        m_strClanAbbr(oOther.m_strClanAbbr),
        m_lstGatherings(oOther.m_lstGatherings),
        m_isLookingToPlay(oOther.m_isLookingToPlay)
    {
    }
    virtual ~DDLCLASS(EidosFriend)() {};
    const DDLCLASS(EidosFriend) &operator=(const DDLCLASS(EidosFriend) &oOther);
    qBool operator==(const DDLCLASS(EidosFriend) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosFriend) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosFriend) *pValue);
    FriendData m_friendData;
    DDLTYPE(string)::CPPType m_strClanAbbr;
    DDLTYPE(std_list)< DDLTYPE(any)< CLASSMETATYPE(Gathering), DDLTYPE(string) > >::CPPType m_lstGatherings;
    DDLTYPE(bool)::CPPType m_isLookingToPlay;
    public:
    protected:
};


class DDLTYPE(EidosFriend): public DDLType {
public:
    typedef EidosFriend CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosFriend)& oEidosFriend) {
        DDLCLASS(EidosFriend)::Add(pMessageToSend,oEidosFriend);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosFriend)* pEidosFriendToRefresh) {
        DDLCLASS(EidosFriend)::Extract(pReceivedMessage,pEidosFriendToRefresh);
    }
};

class EidosFriend: public DDLCLASS(EidosFriend) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosFriendDDL.h_H_
