// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosClanNoticeDDL_H_
#define _EidosClanNoticeDDL_H_

#include <NetZ.h>

BEGIN_NAMESPACE_QUAZAL;
class EidosClanNotice;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosClanNotice): public RootObject {
public:
    DDLCLASS(EidosClanNotice)() {};
    DDLCLASS(EidosClanNotice)(const DDLCLASS(EidosClanNotice) &oOther):
        m_From(oOther.m_From),
        m_Body(oOther.m_Body)
    {
    }
    virtual ~DDLCLASS(EidosClanNotice)() {};
    const DDLCLASS(EidosClanNotice) &operator=(const DDLCLASS(EidosClanNotice) &oOther);
    qBool operator==(const DDLCLASS(EidosClanNotice) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosClanNotice) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosClanNotice) *pValue);
    DDLTYPE(string)::CPPType m_From;
    DDLTYPE(string)::CPPType m_Body;
    public:
    protected:
};


class DDLTYPE(EidosClanNotice): public DDLType {
public:
    typedef EidosClanNotice CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosClanNotice)& oEidosClanNotice) {
        DDLCLASS(EidosClanNotice)::Add(pMessageToSend,oEidosClanNotice);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosClanNotice)* pEidosClanNoticeToRefresh) {
        DDLCLASS(EidosClanNotice)::Extract(pReceivedMessage,pEidosClanNoticeToRefresh);
    }
};

class EidosClanNotice: public DDLCLASS(EidosClanNotice) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosClanNoticeDDL.h_H_
