// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosAccountPrivateDDL_H_
#define _EidosAccountPrivateDDL_H_

#include <NetZ.h>
#include "Services/Foundation/Protocol/ProtocolFoundationProperties.h"
#include "Services/Foundation/Protocol/Data.h"

BEGIN_NAMESPACE_QUAZAL;
class EidosAccountPrivate;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosAccountPrivate): public Data {
public:
    DDLCLASS(EidosAccountPrivate)() {};
    DDLCLASS(EidosAccountPrivate)(const DDLCLASS(EidosAccountPrivate) &oOther):
        m_flags(oOther.m_flags),
        m_postalCode(oOther.m_postalCode),
        m_dateOfBirth(oOther.m_dateOfBirth)
    {
    }
    virtual ~DDLCLASS(EidosAccountPrivate)() {};
    const DDLCLASS(EidosAccountPrivate) &operator=(const DDLCLASS(EidosAccountPrivate) &oOther);
    qBool operator==(const DDLCLASS(EidosAccountPrivate) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosAccountPrivate) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosAccountPrivate) *pValue);
    DDLTYPE(byte)::CPPType m_flags;
    DDLTYPE(string)::CPPType m_postalCode;
    DDLTYPE(datetime)::CPPType m_dateOfBirth;
    public:
	_PR_dataclass_methods_pudecl();
    protected:
	_PR_dataclass_methods_prdecl();
};


class DDLTYPE(EidosAccountPrivate): public DDLType {
public:
    typedef EidosAccountPrivate CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosAccountPrivate)& oEidosAccountPrivate) {
        DDLCLASS(EidosAccountPrivate)::Add(pMessageToSend,oEidosAccountPrivate);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosAccountPrivate)* pEidosAccountPrivateToRefresh) {
        DDLCLASS(EidosAccountPrivate)::Extract(pReceivedMessage,pEidosAccountPrivateToRefresh);
    }
};

class EidosAccountPrivate: public DDLCLASS(EidosAccountPrivate) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosAccountPrivateDDL.h_H_
