// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _EidosAccountPublicDDL_H_
#define _EidosAccountPublicDDL_H_

#include <NetZ.h>
#include "Services/Foundation/Protocol/ProtocolFoundationProperties.h"
#include "Services/Foundation/Protocol/Data.h"

BEGIN_NAMESPACE_QUAZAL;
class EidosAccountPublic;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(EidosAccountPublic): public Data {
public:
    DDLCLASS(EidosAccountPublic)() {};
    DDLCLASS(EidosAccountPublic)(const DDLCLASS(EidosAccountPublic) &oOther):
        m_country(oOther.m_country)
    {
    }
    virtual ~DDLCLASS(EidosAccountPublic)() {};
    const DDLCLASS(EidosAccountPublic) &operator=(const DDLCLASS(EidosAccountPublic) &oOther);
    qBool operator==(const DDLCLASS(EidosAccountPublic) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(EidosAccountPublic) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(EidosAccountPublic) *pValue);
    DDLTYPE(uint32)::CPPType m_country;
    public:
	_PR_dataclass_methods_pudecl();
    protected:
	_PR_dataclass_methods_prdecl();
};


class DDLTYPE(EidosAccountPublic): public DDLType {
public:
    typedef EidosAccountPublic CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(EidosAccountPublic)& oEidosAccountPublic) {
        DDLCLASS(EidosAccountPublic)::Add(pMessageToSend,oEidosAccountPublic);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(EidosAccountPublic)* pEidosAccountPublicToRefresh) {
        DDLCLASS(EidosAccountPublic)::Extract(pReceivedMessage,pEidosAccountPublicToRefresh);
    }
};

class EidosAccountPublic: public DDLCLASS(EidosAccountPublic) {
};


END_NAMESPACE_QUAZAL;

#endif // _EidosAccountPublicDDL.h_H_
