// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosClanInviteDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosClanInvite) & DDLCLASS(EidosClanInvite)::operator=(const DDLCLASS(EidosClanInvite) &oOther){
    m_InviterClanID = oOther.m_InviterClanID;
    m_InviterClanAbbr = oOther.m_InviterClanAbbr;
    m_InviterClanName = oOther.m_InviterClanName;
    m_InviterPlayer = oOther.m_InviterPlayer;
    m_InviterClanRank = oOther.m_InviterClanRank;
    m_InviterClanMembers = oOther.m_InviterClanMembers;
    m_InviteePlayer = oOther.m_InviteePlayer;
    m_IsNew = oOther.m_IsNew;
    return *this;
}

qBool DDLCLASS(EidosClanInvite)::operator==(const DDLCLASS(EidosClanInvite) &oOther) const {
    if (!(m_InviterClanID == oOther.m_InviterClanID)) {return false;}
    if (!(m_InviterClanAbbr == oOther.m_InviterClanAbbr)) {return false;}
    if (!(m_InviterClanName == oOther.m_InviterClanName)) {return false;}
    if (!(m_InviterPlayer == oOther.m_InviterPlayer)) {return false;}
    if (!(m_InviterClanRank == oOther.m_InviterClanRank)) {return false;}
    if (!(m_InviterClanMembers == oOther.m_InviterClanMembers)) {return false;}
    if (!(m_InviteePlayer == oOther.m_InviteePlayer)) {return false;}
    if (!(m_IsNew == oOther.m_IsNew)) {return false;}
    return true;
}

void DDLCLASS(EidosClanInvite)::Add(Message *pMessageToSend, const DDLCLASS(EidosClanInvite) &oValue) {
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.m_InviterClanID);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_InviterClanAbbr);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_InviterClanName);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_InviterPlayer);
    DDLTYPE(int32)::Add(pMessageToSend, oValue.m_InviterClanRank);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.m_InviterClanMembers);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_InviteePlayer);
    DDLTYPE(bool)::Add(pMessageToSend, oValue.m_IsNew);
};

void DDLCLASS(EidosClanInvite)::Extract(Message *pReceivedMessage, DDLCLASS(EidosClanInvite) *pValue) {
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->m_InviterClanID);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_InviterClanAbbr);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_InviterClanName);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_InviterPlayer);
    DDLTYPE(int32)::Extract(pReceivedMessage, &pValue->m_InviterClanRank);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->m_InviterClanMembers);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_InviteePlayer);
    DDLTYPE(bool)::Extract(pReceivedMessage, &pValue->m_IsNew);
};

END_NAMESPACE_QUAZAL;
