// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/EidosAccountPublicDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(EidosAccountPublic) & DDLCLASS(EidosAccountPublic)::operator=(const DDLCLASS(EidosAccountPublic) &oOther){
    m_country = oOther.m_country;
    return *this;
}

qBool DDLCLASS(EidosAccountPublic)::operator==(const DDLCLASS(EidosAccountPublic) &oOther) const {
    if (!(m_country == oOther.m_country)) {return false;}
    return true;
}

void DDLCLASS(EidosAccountPublic)::Add(Message *pMessageToSend, const DDLCLASS(EidosAccountPublic) &oValue) {
    Data::Add(pMessageToSend,oValue);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.m_country);
};

void DDLCLASS(EidosAccountPublic)::Extract(Message *pReceivedMessage, DDLCLASS(EidosAccountPublic) *pValue) {
    Data::Extract(pReceivedMessage,pValue);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->m_country);
};

_PR_dataclass_methods_derived_impl(EidosAccountPublic,Data);
END_NAMESPACE_QUAZAL;
