// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _OSIDDF_H_
#define _OSIDDF_H_


#include <NetZ.h>

BEGIN_NAMESPACE_QUAZAL;


class OSIDDLDeclarations : public DDLDeclarations {
	public:
		static void Register();
		static void RegisterParseTree();
		virtual void Init();
};


END_NAMESPACE_QUAZAL;

#endif // _OSIDDF.h_H_
