// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/TTLRoundDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(TTLRound) & DDLCLASS(TTLRound)::operator=(const DDLCLASS(TTLRound) &oOther){
    isPrivate = oOther.isPrivate;
    levelIndex = oOther.levelIndex;
    gameType = oOther.gameType;
    timeLimit = oOther.timeLimit;
    levelName = oOther.levelName;
    ranking = oOther.ranking;
    return *this;
}

qBool DDLCLASS(TTLRound)::operator==(const DDLCLASS(TTLRound) &oOther) const {
    if (!(isPrivate == oOther.isPrivate)) {return false;}
    if (!(levelIndex == oOther.levelIndex)) {return false;}
    if (!(gameType == oOther.gameType)) {return false;}
    if (!(timeLimit == oOther.timeLimit)) {return false;}
    if (!(levelName == oOther.levelName)) {return false;}
    if (!(ranking == oOther.ranking)) {return false;}
    return true;
}

void DDLCLASS(TTLRound)::Add(Message *pMessageToSend, const DDLCLASS(TTLRound) &oValue) {
    Gathering::Add(pMessageToSend,oValue);
    DDLTYPE(bool)::Add(pMessageToSend, oValue.isPrivate);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.levelIndex);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.gameType);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.timeLimit);
    DDLTYPE(string)::Add(pMessageToSend, oValue.levelName);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.ranking);
};

void DDLCLASS(TTLRound)::Extract(Message *pReceivedMessage, DDLCLASS(TTLRound) *pValue) {
    Gathering::Extract(pReceivedMessage,pValue);
    DDLTYPE(bool)::Extract(pReceivedMessage, &pValue->isPrivate);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->levelIndex);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->gameType);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->timeLimit);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->levelName);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->ranking);
};

_PR_gathering_methods_derived_impl(TTLRound,Gathering);
END_NAMESPACE_QUAZAL;
