// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _TTLStatsDDL_H_
#define _TTLStatsDDL_H_

#include <NetZ.h>
#include "Extensions/STL/STLExtTypes.h"

BEGIN_NAMESPACE_QUAZAL;
class TTLStats;
END_NAMESPACE_QUAZAL;

BEGIN_NAMESPACE_QUAZAL;

class DDLCLASS(TTLStats): public RootObject {
public:
    DDLCLASS(TTLStats)() {};
    DDLCLASS(TTLStats)(const DDLCLASS(TTLStats) &oOther):
        m_strPlayer(oOther.m_strPlayer),
        m_strClanAbbr(oOther.m_strClanAbbr),
        m_clanRating(oOther.m_clanRating),
        m_clanKills(oOther.m_clanKills),
        m_pidPlayer(oOther.m_pidPlayer),
        m_lstValues(oOther.m_lstValues)
    {
    }
    virtual ~DDLCLASS(TTLStats)() {};
    const DDLCLASS(TTLStats) &operator=(const DDLCLASS(TTLStats) &oOther);
    qBool operator==(const DDLCLASS(TTLStats) &oOther) const;
    static void Add(Message *pMessageToSend, const DDLCLASS(TTLStats) &oValue);
    static void Extract(Message *pReceivedMessage, DDLCLASS(TTLStats) *pValue);
    DDLTYPE(string)::CPPType m_strPlayer;
    DDLTYPE(string)::CPPType m_strClanAbbr;
    DDLTYPE(float)::CPPType m_clanRating;
    DDLTYPE(float)::CPPType m_clanKills;
    DDLTYPE(uint32)::CPPType m_pidPlayer;
    DDLTYPE(std_list)< DDLTYPE(float) >::CPPType m_lstValues;
    public:
    protected:
};


class DDLTYPE(TTLStats): public DDLType {
public:
    typedef TTLStats CPPType;
    static void Add(Message* pMessageToSend, const DDLCLASS(TTLStats)& oTTLStats) {
        DDLCLASS(TTLStats)::Add(pMessageToSend,oTTLStats);
    }
    static void Extract(Message* pReceivedMessage, DDLCLASS(TTLStats)* pTTLStatsToRefresh) {
        DDLCLASS(TTLStats)::Extract(pReceivedMessage,pTTLStatsToRefresh);
    }
};

class TTLStats: public DDLCLASS(TTLStats) {
};


END_NAMESPACE_QUAZAL;

#endif // _TTLStatsDDL.h_H_
