// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "OSI/PS2/TTLStatsDDL.h"

BEGIN_NAMESPACE_QUAZAL;

const DDLCLASS(TTLStats) & DDLCLASS(TTLStats)::operator=(const DDLCLASS(TTLStats) &oOther){
    m_strPlayer = oOther.m_strPlayer;
    m_strClanAbbr = oOther.m_strClanAbbr;
    m_clanRating = oOther.m_clanRating;
    m_clanKills = oOther.m_clanKills;
    m_pidPlayer = oOther.m_pidPlayer;
    m_lstValues = oOther.m_lstValues;
    return *this;
}

qBool DDLCLASS(TTLStats)::operator==(const DDLCLASS(TTLStats) &oOther) const {
    if (!(m_strPlayer == oOther.m_strPlayer)) {return false;}
    if (!(m_strClanAbbr == oOther.m_strClanAbbr)) {return false;}
    if (!(m_clanRating == oOther.m_clanRating)) {return false;}
    if (!(m_clanKills == oOther.m_clanKills)) {return false;}
    if (!(m_pidPlayer == oOther.m_pidPlayer)) {return false;}
    if (!(m_lstValues == oOther.m_lstValues)) {return false;}
    return true;
}

void DDLCLASS(TTLStats)::Add(Message *pMessageToSend, const DDLCLASS(TTLStats) &oValue) {
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_strPlayer);
    DDLTYPE(string)::Add(pMessageToSend, oValue.m_strClanAbbr);
    DDLTYPE(float)::Add(pMessageToSend, oValue.m_clanRating);
    DDLTYPE(float)::Add(pMessageToSend, oValue.m_clanKills);
    DDLTYPE(uint32)::Add(pMessageToSend, oValue.m_pidPlayer);
    DDLTYPE(std_list)< DDLTYPE(float) >::Add(pMessageToSend, oValue.m_lstValues);
};

void DDLCLASS(TTLStats)::Extract(Message *pReceivedMessage, DDLCLASS(TTLStats) *pValue) {
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_strPlayer);
    DDLTYPE(string)::Extract(pReceivedMessage, &pValue->m_strClanAbbr);
    DDLTYPE(float)::Extract(pReceivedMessage, &pValue->m_clanRating);
    DDLTYPE(float)::Extract(pReceivedMessage, &pValue->m_clanKills);
    DDLTYPE(uint32)::Extract(pReceivedMessage, &pValue->m_pidPlayer);
    DDLTYPE(std_list)< DDLTYPE(float) >::Extract(pReceivedMessage, &pValue->m_lstValues);
};

END_NAMESPACE_QUAZAL;
