#ifndef __VU_MICRO_ID_H
#define __VU_MICRO_ID_H

namespace VUMicro
{

enum
{
	ANIM_FINISH,
	ANIM_LOAD_STREAM_TO_CACHE,
	ANIM_LOAD_CACHE_TO_MTX_1,
	ANIM_LOAD_CACHE_TO_MTX_2,
	ANIM_LOAD_CACHE_TO_MTX_3,
	ANIM_LOAD_CACHE_TO_MTX_4,
	ANIM_LOAD_STREAM_TO_MTX_1,
	ANIM_LOAD_STREAM_TO_MTX_2,
	ANIM_LOAD_STREAM_TO_MTX_3,
	ANIM_LOAD_STREAM_TO_MTX_4,
	ANIM_LOAD_NEXT_INST,
	ANIM_TRANSFORM_MTX_1_START,
	ANIM_TRANSFORM_MTX_2_START,
	ANIM_TRANSFORM_MTX_3_START,
	ANIM_TRANSFORM_MTX_4_START,
	ANIM_TRANSFORM_MTX_1_CONT_NW,
	ANIM_TRANSFORM_MTX_2_CONT_NW,
	ANIM_TRANSFORM_MTX_3_CONT_NW,
	ANIM_TRANSFORM_MTX_4_CONT_NW,
	ANIM_TRANSFORM_MTX_1_CONT,
	ANIM_TRANSFORM_MTX_2_CONT,
	ANIM_TRANSFORM_MTX_3_CONT,
	ANIM_TRANSFORM_MTX_4_CONT,
	ANIM_TRANSFORM_MTX_1_CONT_NR,
	ANIM_TRANSFORM_MTX_2_CONT_NR,
	ANIM_TRANSFORM_MTX_3_CONT_NR,
	ANIM_TRANSFORM_MTX_4_CONT_NR,
	ANIM_TRANSFORM_FINISH,
	
	ANIM_MAX_INSTRUCTIONS,
	
	ANIM_MICRO_END = 0xffffffff
} ;



enum
{
	ANIML_FINISH,
	ANIML_LOAD_STREAM_TO_CACHE,
	ANIML_LOAD_CACHE_TO_MTX_1,
	ANIML_LOAD_CACHE_TO_MTX_2,
	ANIML_LOAD_STREAM_TO_MTX_1,
	ANIML_LOAD_STREAM_TO_MTX_2,
	ANIML_LOAD_NEXT_INST,
	ANIML_TRANSFORM_PROCESS_INST,
	ANIML_TRANSFORM_MTX_1_START,
	ANIML_TRANSFORM_MTX_1_CONT_NW,
	ANIML_TRANSFORM_MTX_1_CONT_NW_ADC,
	ANIML_TRANSFORM_MTX_1_CONT,
	ANIML_TRANSFORM_MTX_1_CONT_ADC,
	ANIML_TRANSFORM_MTX_1_CONT_NR,
	ANIML_TRANSFORM_MTX_1_CONT_NR_ADC,
	ANIML_TRANSFORM_MTX_2_START,
	ANIML_TRANSFORM_MTX_2_CONT_NW,
	ANIML_TRANSFORM_MTX_2_CONT_NW_ADC,
	ANIML_TRANSFORM_MTX_2_CONT,
	ANIML_TRANSFORM_MTX_2_CONT_ADC,
	ANIML_TRANSFORM_MTX_2_CONT_NR,
	ANIML_TRANSFORM_MTX_2_CONT_NR_ADC,
	ANIML_TRANSFORM_FINISH,
	ANIML_TRANSFORM_FINISH_ADC,
	
	ANIML_MAX_INSTRUCTIONS,

	ANIML_MICRO_END = 0xffffffff
} ;

}

#endif