#ifndef _INCLUDED_OSI_GAME_CONFIG_
#define _INCLUDED_OSI_GAME_CONFIG_

#define OSI_MAX_LOCAL_PLAYERS		(1)
#define OSI_MAX_REMOTE_PLAYERS		(15)
#define OSI_MAX_PLAYERS				(OSI_MAX_LOCAL_PLAYERS + OSI_MAX_REMOTE_PLAYERS)
#define OSI_MAX_CLAN_MEMBERS		(100)

#endif // _INCLUDED_OSI_GAME_CONFIG_
