
#include "OSIStringTable.hpp"

OSIchar *OSIStringTable[ OSI_END_TEXT_LIST ] =
{
	"REQUEST FOR INVALID STRING IN THE STRING TABLE",
	"Idling...",
	"Activating Hardware...",
	"Processing account list...",
	"Logging in...",
	"Processing Host Match...",
	"Processing Find Match...",
	"Processing...",
	"Retrieving friends list...",															 
	"Logging in...",
	"DNAS Authentication...",
	"Connecting to Authentication Service...",
	"Requesting Login...",
	"Waiting for Login...",
	"Connecting to Account Serivce...",
	"Connecting to Friends Service...",
	"Connecting to MatchMaking Service...",
	"Processing...",														 
	"Creating a new match...",
	"Registering new match with servers...",
	"Waiting on match registration...",
	"Requesting to join match...",
	"Joining match...",
	"Registering with statistics server...",
	"Waiting on statistics registration...",
	"Preparing to launch match...",
	"Waiting to launch match...",															 
	"Confirming connectivity...",
	"Requesting the friends list...",
	"Waiting for the friends list...",
	"Requesting incoming match invitations...",
	"Waiting for incoming match invitations...",
	"Requesting outgoing match invitations...",
	"Waiting for outgoing match invitations...",
	"Requesting invitation status update...",
	"Waiting for invitation status update...",															 
	"Requesting a default query...",
	"Requesting a custom query...",
	"Requesting a statistics query...",
	"Waiting for default query...",
	"Waiting for custom query...",
	"Waiting for statistics query...",
	"Getting connection info...",
	"Waiting on connection info...",														 
	"Performing DNAS Authorization...",														 
	"Requesting match participation...",
	"Waiting for match participation...",
	"Requesting URL to the match...",
	"Waiting for URL to the match...",
	"Making match connection...",															 
	"Requesting account creation...",
	"Waiting for account creation...",
	"Logging out...",														 
	"Starting round...",
	"Waiting for round to start...",
	"Checking for round invitation...",
	"Waiting for round invitation...",														 
	"Finishing round...",
	"Waiting on round finishing...",
	"Reporting statistics...",
	"Waiting on statistics reporting...",
	"Deleting round...",
	"Waiting on round deletion...",														 
	"Finishing the match...",
	"Waiting for the match to finish...",
	"Deleting the match...",
	"Waiting on match deletion...",														 
	"Waiting on statistics registration...",
	"Waiting on invitation...",
	"Inviting opponent to round...",
														 
	// GENERAL ERRORS
	"Unable to start new request, previous request still in progress.",

	// FRIEND ERRORS
	"You have already sent that player a friend request.  That player is either waiting to accept the request, has already accepted the request, or has blocked the request.",
	"That player no longer has a friends request offered.",
	"That player's friendship offer no longer exists.",
	"That player's friend request was not available to block.",
	"A problem occurred when trying to unblock the friend request.",
	"A problem occurred when trying to offer friendship.",
	"That friendship request no longer exists.",
	"That friendship request no longer exists.",
	"Please choose someone other than yourself to send a request to.",
	"The player invited does not exist.",
	"You have reached your friend limit of 100.",
	"The person you are trying to offer friendship to has reached the friend limit of 100.",
												 
	// DNAS Errors
	"The network authentication server is busy.  Please try again later.", // OSIPS2_DNAS_AUTH_SERVER_BUSY
	"This software title is not in service.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIPS2_DNAS_SOFTWARE_
	"The network authentication server is not in service.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIPS2_
	"Connection to the network authentication server has timed out.  Please try again later.", // OSIPS2_DNAS_AUTH_SERVER_TIMEOUT
	"A network authentication system error has occurred.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIPS2_DN
	"A PlayStation®2 hardware information error has occurred.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIP
	"A PlayStation®2 disc information error has occurred.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIPS2_D
	"Network connection has been aborted.", // OSIPS2_DNAS_NETWORK_CONNECTION_ABORTED
	"Error in proxy setting.", // OSIPS2_DNAS_ERROR_IN_PROXY_SETTING
	"Connection time out.  Please try connecting again at a later time.", // OSIPS2_DNAS_CONNECTION_TIMEOUT
	"There was no repsone from the DNS sever.  Please check your network configuration.", // OSIPS2_DNAS_DNS_NO_RESPONSE
	"There was an error in the response from the DNS server.  Please check your network connection.", // OSIPS2_DNAS_DNS_RESPONSE_ERROR
	"There was a DNS error.  Please check your network configuration.", // OSIPS2_DNAS_DNS_ERROR
	"Connection to DNAS server failed.", // OSIPS2_DNAS_CONNECTION_TO_DNAS_FAILED
	"There was a connection error.", // OSIPS2_DNAS_CONNECTION_ERROR
	"An authentication error has occurred.  Please write down the error code number, and contact SCEA at 1-866-466-5333 or via SCEA's website, www.us.playstation.com.", // OSIPS2_DNAS_AUTH_ERROR
	"An unspecified error has occurred.", // OSIPS2_DNAS_UNSPECIFIED_ERROR



	// RendezVous specific errors
	"An unspecified clan error has occurred.",
	"You do not have permission to perform this action.",
	"That player is no longer in the clan.",
	"The clan specified for the request is invalid.",
	"The player invited does not exist.",
	"That clan abbreviation is already taken, please try a different abbreviation.",
	"That clan name is already taken, please try a different name.",
	"You are currently already in a clan.  Please leave your clan before attempting this action.",
	"You have already sent that player a clan invitation.  That player is either waiting to accept the request or has blocked the request.",
	"This player is currently not accepting clan invites.",
	"The invitation is invalid.",
	"You must either transfer leadership to an officer or be the only member of your clan to leave it as the leader.",
	"The clan is currently full.",
	"That clan name is not allowed, please try a different name.",
	"That player is already in your clan.",

	// OTHER ERRORS
	"Failed to connect to online service.",
	"Failed to authenticate with online service.",
	"Invalid user name.",
	"Invalid password.",
	"User name already exists.",
	"Invalid account name, or account disabled.",
	"Someone is currently logged in using this account.",
	"Encryption error.",
	"Invalid user name (name was filtered).",
	"Invalid text used (text was filtered).",
	"You do not have permission to invite players to this match.",
	"This player is already invited to your match.",
	"Failed to request match participation.",
	"Failed to retrieve match participants.",
	"Failed to request match IP address.",
	"Failed to retrieve match IP address.",
	"Failed to connect to match IP address.",

	//--------------------------------------------------------------------
	//            F A T A L   E R R O R S
	//--------------------------------------------------------------------
	"",
	"Unable to process request for friends list.",
	"Unable to process request for authorizing friendship.",
	"Unable to process request for denying friendship.",
	"Unable to process request for blocking friendship.",
	"Unable to process request for unblocking friendship.",
	"Unable to process request for offering friendship.",
	"Unable to process request for canceling friendship offer.",
	"Unable to process request for ending friendship.",
	"Failed to connect to Authentication Service.",
	"Failed to activate account.",
	"Failed to verify account.",
	"Failed to connect to Connection server.",
	"Failed to connect to Account server.",
	"Failed to connect to Friends server.",
	"Failed to connect to MatchMaking server.",
	"Failed to connect to Statistics server.",
	"Failed to find account.",
	"Failed to create new request context.",
	"Failed to create BackEnd service.",
	"Failed to connect to Friends service.",
	"Failed to create match.",
	"Failed to request participation in match.",
	"Failed to participate in match.",
	"Failed to register match with statistics server.",
	"Failed to begin launching match.",
	"Failed to launch match.",
	"Failed to begin launching round.",
	"Failed to launch round.",
	"Match ended while attempting to join it.",
	"Failed to participate in match.",
	"Failed to request default matches.",
	"Failed to request custom matches.",
	"Failed to request connection status.",
	"Failed to connect to network hardware.",
	"Failed to process request for fetching the match URL.",
	"Failed to process request in time.",
	"Failed to start round.",
	"Failed while waiting for start round.",
	"Failed to finish round.",
	"Failed while waiting for finish round.",
	"Failed to report statistics.",
	"Failed while waiting to report statistics.",
	"Failed to end participation.",
	"Failed while waiting to end participation.",
	"Failed to finish the match.",
	"Failed while waiting to finish the match.",
	"Failed to end the match.",
	"Failed while waiting to end the match.",
	"Failed to find round invitation.",
	"Failed to invite opponents to round.",
	"Failed to register round with statistics server.",
	"Connection to network lost. Please try again.",
	"Failed to create new account.",
	"Failed to find a match.",
	"Failed to find the match specified.",
	"Failed to invite player to match.",																 
	"Failed to start the Peer-to-Peer Service.  Please try again later.",
	"Failed to start NAT Traversal.  Please try again later.",
	"Failed to find the statistics service.",
	"Failed to create statistics request.",
	"Failed to register a new statistics request.",
	"Failed to update player status.",
	"Failed to retrieve player statistics.",
	"Failed to retrieve clan statistics.",
	"Failed to retrieve ranking statistics.",
	"Failed to process request for retrieving match invitations.",
	"Failed to process request for finding player from name.",
	"Failed to process request for creating clan.",
	"Failed to process request for retrieving clan information.",
	"Failed to process request for joining clan by invitation.",
	"Failed to process request for denying the clan invitation.",
	"Failed to process request for blocking sender of clan invitation.",
	"Failed to process request for sending clan invitation.",
	"Failed to process request for canceling sent clan invitation.",
	"Failed to process request for clan invitation list.",
	"Failed to process request for clan ID list.",
	"Failed to process request for clan information list.",
	"Failed to process request for clan membership list.",
	"Failed to process request for leaving current clan.",
	"Failed to process request for clan notice list.",
	"Failed to process request for posting clan notice.",
	"Failed to process request for kicking clan member.",
	"Failed to process request for demoting clan member.",
	"Failed to process request for promoting clan member.",
	"Failed to process request for transfering clan leadership.",
	"Failed to process request for filtering text for profanity.",
	"Failed to process request for message of the day.",
	"Failed to process request for player joining match.",
	"Failed to process request for player leaving match.",
	"Failed to find the hosted match.",
};


	