// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOActorDDL_H_
#define _DOActorDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSBuffer.h"
#include "Network/NetZ/DSActorInteraction.h"
#include "Network/NetZ/DSBuffer.h"
#include "Network/NetZ/DSBuffer.h"
#include "Network/NetZ/DSActorMigrate.h"
#include "Network/NetZ/DSActorProps.h"
#include "Network/NetZ/DOMessageOwner.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOActor;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOActor): public DOMessageOwner {
public:
	_DO_DeclareGeneralMethods(DOActor);

	_DSDECL_DSBuffer	d_configData;
	_DSDECL_DSActorInteraction	d_interaction;
	_DSDECL_DSBuffer	d_masterData;
	_DSDECL_DSBuffer	d_masterMetaData;
	_DSDECL_DSActorMigrate	d_migrate;
	_DSDECL_DSActorProps	d_props;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOActor);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOActor: public DOClassTemplate<DOCLASS(DOActor), _DOC_DOMessageOwner> {
public:
	_DOC_DeclareGeneralMethods(DOActor)
};
END_NAMESPACE_QUAZAL;

#endif // _DOActorDDL_H_
