// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOGenericDDL_H_
#define _DOGenericDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSVector.h"
#include "Network/NetZ/DSSixDOF.h"
#include "Network/NetZ/AvalancheProperties.h"
#include "Network/NetZ/DOActor.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOGeneric;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOGeneric): public DOActor {
public:
	_DO_DeclareGeneralMethods(DOGeneric);

	_DSDECL_DSVector	d_acceleration;
	_DSDECL_DSSixDOF	d_state;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOGeneric);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOGeneric: public DOClassTemplate<DOCLASS(DOGeneric), _DOC_DOActor> {
public:
	_DOC_DeclareGeneralMethods(DOGeneric)
};
END_NAMESPACE_QUAZAL;

#endif // _DOGenericDDL_H_
