// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOHostDDL_H_
#define _DOHostDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSSessionLock.h"
#include "Network/NetZ/DSHostState.h"
#include "Network/NetZ/DOMessageOwner.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOHost;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOHost): public DOMessageOwner {
public:
	_DO_DeclareGeneralMethods(DOHost);

	_DSDECL_DSSessionLock	d_lock;
	_DSDECL_DSHostState	d_state;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOHost);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOHost: public DOClassTemplate<DOCLASS(DOHost), _DOC_DOMessageOwner> {
public:
	_DOC_DeclareGeneralMethods(DOHost)
};
END_NAMESPACE_QUAZAL;

#endif // _DOHostDDL_H_
