// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOMessageOwnerDDL_H_
#define _DOMessageOwnerDDL_H_

#include <NetZ.h>
#include "Network/NetZ/AvalancheDDF.h"
class DOMessageOwner;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOMessageOwner): public ROOT_ROOTDO {
public:
	_DO_DeclareGeneralMethods(DOMessageOwner);

	_DO_DeclareRMCStub(PostBuffer, (RMCContext* pCallContext, const DDLTYPE(uint32)::CPPType& i_hash, const DDLTYPE(buffer)::CPPType& i_data, const DDLTYPE(dohandle)::CPPType& i_sender));
	_DO_DeclareRMCStub(PostFlag, (RMCContext* pCallContext, const DDLTYPE(uint32)::CPPType& i_hash, const DDLTYPE(dohandle)::CPPType& i_sender));
	_DO_DeclareRMCStub(SendBuffer, (RMCContext* pCallContext, const DDLTYPE(uint32)::CPPType& i_hash, const DDLTYPE(buffer)::CPPType& i_data, const DDLTYPE(dohandle)::CPPType& i_sender));
	_DO_DeclareRMCStub(SendFlag, (RMCContext* pCallContext, const DDLTYPE(uint32)::CPPType& i_hash, const DDLTYPE(dohandle)::CPPType& i_sender));
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
typedef DDLTYPE(uint32) TPostBuffer_i_hash;
typedef DDLTYPE(buffer) TPostBuffer_i_data;
typedef DDLTYPE(dohandle) TPostBuffer_i_sender;
typedef DDLTYPE(uint32) TPostFlag_i_hash;
typedef DDLTYPE(dohandle) TPostFlag_i_sender;
typedef DDLTYPE(uint32) TSendBuffer_i_hash;
typedef DDLTYPE(buffer) TSendBuffer_i_data;
typedef DDLTYPE(dohandle) TSendBuffer_i_sender;
typedef DDLTYPE(uint32) TSendFlag_i_hash;
typedef DDLTYPE(dohandle) TSendFlag_i_sender;
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOMessageOwner);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOMessageOwner: public DOClassTemplate<DOCLASS(DOMessageOwner), _DOC_ROOT_ROOTDO> {
public:
	_DOC_DeclareGeneralMethods(DOMessageOwner)
	_DOC_DeclareRMC(PostBuffer);
	_DOC_DeclareRMC(PostFlag);
	_DOC_DeclareRMC(SendBuffer);
	_DOC_DeclareRMC(SendFlag);
};
END_NAMESPACE_QUAZAL;

#endif // _DOMessageOwnerDDL_H_
