// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include <NetZ.h>
#include "Network/NetZ/DOPathFollowerDDL.h"
#include "Network/NetZ/DOPathFollower.h"
BEGIN_NAMESPACE_QUAZAL;

_DOC_ImplementSomeGeneralMethods(DOPathFollower)
_PR_userdo_derived_impl(DOPathFollower,DOActor);
_PR_globaldo_derived_impl(DOPathFollower,DOActor);

_DOC_DOPathFollower::_DOC_DOPathFollower(qUnsignedInt32 uiClassID):
	DOClassTemplate<DOCLASS(DOPathFollower), _DOC_DOActor>(uiClassID) {
}

bool _DOC_DOPathFollower::IsAKindOf(DOClassID idDOCID) {
	if(DOCLASSID(DOPathFollower) == idDOCID) return true;
	return _DOC_DOActor::IsAKindOf(idDOCID);
}
void _DOC_DOPathFollower::DataSetsOperation(qUnsignedInt32 uiOp) {
	_DOC_DOActor::DataSetsOperation(uiOp);
	_DOC_RegisterProtocol(7,_PR_basic_update_protocol_protodecl( _DSDECL_DSPathFollower ));
	typedef DeadReckoningFilter<_DSDECL_DSPathFollower,_PR_DRPathFollower_model(DSPathFollower)> Filter_DSPathFollower_DRPathFollower;
	_DOC_RegisterFilter(7,Filter_DSPathFollower_DRPathFollower);
	_DSDECL_DSPathFollower::RegisterCounters(uiOp);
};
qBool _DOC_DOPathFollower::FormatVariableValue(const DuplicatedObject *pDO, Variable *pDataset, Variable *pVariable, NS_QUAZAL String *pstrResult) const {
	_DOC_FormatMatchingVariableValue(DOPathFollower,d_state);
	return _DOC_DOActor::FormatVariableValue(pDO, pDataset, pVariable, pstrResult);
}

bool _DOC_DOPathFollower::DispatchAction(DuplicatedObject* pDO, MethodID idMethod, Message* pMsg) {
	return _DOC_DOActor::DispatchAction(pDO, idMethod, pMsg);
}

bool _DOC_DOPathFollower::DispatchRMCCall(CallMethodOperation* pContext) {
	return _DOC_DOActor::DispatchRMCCall(pContext);
}

bool _DOC_DOPathFollower::DispatchRMCResult(RMCContext* pContext) {
	return _DOC_DOActor::DispatchRMCResult(pContext);
}


void _DOC_DOPathFollower::FillDupSpacesInfo(DupSpace::Role eRole, DupSpace::ID* pArray, qUnsignedInt* puiIndex) {
	_DOC_DOActor::FillDupSpacesInfo(eRole, pArray, puiIndex);
}


_DO_DOPathFollower::_DO_DOPathFollower()  {_DO_InitDO(DOPathFollower);}

_DO_ImplementSomeGeneralMethods(DOPathFollower);



void _DO_DOPathFollower::RegisterDatasets() {
	_DO_RegisterDataset(d_state);
}

void _DO_DOPathFollower::SpecificAddDSToDiscoveryMessage(Message* pMsg, Station* pStation) {
	_DO_DSAddToDiscovery(d_state,pStation,7);
	DOActor::SpecificAddDSToDiscoveryMessage(pMsg, pStation);
}

void _DO_DOPathFollower::SpecificExtractDSFromDiscoveryMessage(Message* pMsg) {
	_DO_DSExtractFromDiscovery(d_state,7);
	DOActor::SpecificExtractDSFromDiscoveryMessage(pMsg);
}

void _DO_DOPathFollower::CallOperationOnDatasets(DOOperation* pOperation, Operation::Event eEvent) {
	_DO_CallOperationOnDataset(d_state,7);
	DOActor::CallOperationOnDatasets(pOperation,eEvent);
}

bool _DO_DOPathFollower::SpecificUpdate(DataSet *pDataset, const Time& tUpdateTime) {
	_DO_DatasetUpdate(d_state,7);
	return DOActor::SpecificUpdate(pDataset, tUpdateTime);
}

bool _DO_DOPathFollower::SpecificRefresh(DataSet *pDataset, const Time& tRefreshTime) {
	_DO_DataSetRefresh(d_state);
	return DOActor::SpecificRefresh(pDataset, tRefreshTime);
}

bool _DO_DOPathFollower::SpecificExtractADataset(Message* pMsg, qByte byDatasetIndex) { 

	switch (byDatasetIndex) {
		_DO_DSExtract(d_state,7);
	}
	return DOActor::SpecificExtractADataset(pMsg, byDatasetIndex);
}

END_NAMESPACE_QUAZAL;
