// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOPathFollowerDDL_H_
#define _DOPathFollowerDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSPathFollower.h"
#include "Network/NetZ/AvalancheProperties.h"
#include "Network/NetZ/DOActor.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOPathFollower;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOPathFollower): public DOActor {
public:
	_DO_DeclareGeneralMethods(DOPathFollower);

	_DSDECL_DSPathFollower	d_state;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOPathFollower);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOPathFollower: public DOClassTemplate<DOCLASS(DOPathFollower), _DOC_DOActor> {
public:
	_DOC_DeclareGeneralMethods(DOPathFollower)
};
END_NAMESPACE_QUAZAL;

#endif // _DOPathFollowerDDL_H_
