// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOTalkerDDL_H_
#define _DOTalkerDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSTalkerProps.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOTalker;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOTalker): public ROOT_ROOTDO {
public:
	_DO_DeclareGeneralMethods(DOTalker);

	_DSDECL_DSTalkerProps	d_props;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOTalker);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOTalker: public DOClassTemplate<DOCLASS(DOTalker), _DOC_ROOT_ROOTDO> {
public:
	_DOC_DeclareGeneralMethods(DOTalker)
};
END_NAMESPACE_QUAZAL;

#endif // _DOTalkerDDL_H_
