// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include <NetZ.h>
#include "Network/NetZ/DOWorldDDL.h"
#include "Network/NetZ/DOWorld.h"
BEGIN_NAMESPACE_QUAZAL;

_DOC_ImplementSomeGeneralMethods(DOWorld)
_PR_userdo_derived_impl(DOWorld,DOMessageOwner);
_PR_globaldo_derived_impl(DOWorld,DOMessageOwner);

_DOC_DOWorld::_DOC_DOWorld(qUnsignedInt32 uiClassID):
	DOClassTemplate<DOCLASS(DOWorld), _DOC_DOMessageOwner>(uiClassID) {
}

bool _DOC_DOWorld::IsAKindOf(DOClassID idDOCID) {
	if(DOCLASSID(DOWorld) == idDOCID) return true;
	return _DOC_DOMessageOwner::IsAKindOf(idDOCID);
}
void _DOC_DOWorld::DataSetsOperation(qUnsignedInt32 uiOp) {
	_DOC_DOMessageOwner::DataSetsOperation(uiOp);
	_DOC_RegisterProtocol(1,_PR_basic_update_protocol_protodecl( _DSDECL_DSWorldExtents ));
	_DOC_RegisterFilter(1,_PR_upon_request_filter_filterdecl( _DSDECL_DSWorldExtents ));
	_DOC_RegisterProtocol(2,_PR_basic_update_protocol_protodecl( _DSDECL_DSStartTime ));
	_DOC_RegisterFilter(2,_PR_upon_request_filter_filterdecl( _DSDECL_DSStartTime ));
	_DSDECL_DSWorldExtents::RegisterCounters(uiOp);
	_DSDECL_DSStartTime::RegisterCounters(uiOp);
};
qBool _DOC_DOWorld::FormatVariableValue(const DuplicatedObject *pDO, Variable *pDataset, Variable *pVariable, NS_QUAZAL String *pstrResult) const {
	_DOC_FormatMatchingVariableValue(DOWorld,d_extents);
	_DOC_FormatMatchingVariableValue(DOWorld,d_start);
	return _DOC_DOMessageOwner::FormatVariableValue(pDO, pDataset, pVariable, pstrResult);
}

bool _DOC_DOWorld::DispatchAction(DuplicatedObject* pDO, MethodID idMethod, Message* pMsg) {
	return _DOC_DOMessageOwner::DispatchAction(pDO, idMethod, pMsg);
}

bool _DOC_DOWorld::DispatchRMCCall(CallMethodOperation* pContext) {
	return _DOC_DOMessageOwner::DispatchRMCCall(pContext);
}

bool _DOC_DOWorld::DispatchRMCResult(RMCContext* pContext) {
	return _DOC_DOMessageOwner::DispatchRMCResult(pContext);
}


void _DOC_DOWorld::FillDupSpacesInfo(DupSpace::Role eRole, DupSpace::ID* pArray, qUnsignedInt* puiIndex) {
	_DOC_DOMessageOwner::FillDupSpacesInfo(eRole, pArray, puiIndex);
}


_DO_DOWorld::_DO_DOWorld()  {_DO_InitDO(DOWorld);}

_DO_ImplementSomeGeneralMethods(DOWorld);



void _DO_DOWorld::RegisterDatasets() {
	_DO_RegisterDataset(d_extents);
	_DO_RegisterDataset(d_start);
}

void _DO_DOWorld::SpecificAddDSToDiscoveryMessage(Message* pMsg, Station* pStation) {
	_DO_DSAddToDiscovery(d_extents,pStation,1);
	_DO_DSAddToDiscovery(d_start,pStation,2);
	DOMessageOwner::SpecificAddDSToDiscoveryMessage(pMsg, pStation);
}

void _DO_DOWorld::SpecificExtractDSFromDiscoveryMessage(Message* pMsg) {
	_DO_DSExtractFromDiscovery(d_extents,1);
	_DO_DSExtractFromDiscovery(d_start,2);
	DOMessageOwner::SpecificExtractDSFromDiscoveryMessage(pMsg);
}

void _DO_DOWorld::CallOperationOnDatasets(DOOperation* pOperation, Operation::Event eEvent) {
	_DO_CallOperationOnDataset(d_extents,1);
	_DO_CallOperationOnDataset(d_start,2);
	DOMessageOwner::CallOperationOnDatasets(pOperation,eEvent);
}

bool _DO_DOWorld::SpecificUpdate(DataSet *pDataset, const Time& tUpdateTime) {
	_DO_DatasetUpdate(d_extents,1);
	_DO_DatasetUpdate(d_start,2);
	return DOMessageOwner::SpecificUpdate(pDataset, tUpdateTime);
}

bool _DO_DOWorld::SpecificRefresh(DataSet *pDataset, const Time& tRefreshTime) {
	_DO_DataSetRefresh(d_extents);
	_DO_DataSetRefresh(d_start);
	return DOMessageOwner::SpecificRefresh(pDataset, tRefreshTime);
}

bool _DO_DOWorld::SpecificExtractADataset(Message* pMsg, qByte byDatasetIndex) { 

	switch (byDatasetIndex) {
		_DO_DSExtract(d_extents,1);
		_DO_DSExtract(d_start,2);
	}
	return DOMessageOwner::SpecificExtractADataset(pMsg, byDatasetIndex);
}

END_NAMESPACE_QUAZAL;
