// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DOWorldDDL_H_
#define _DOWorldDDL_H_

#include <NetZ.h>
#include "Network/NetZ/DSWorldExtents.h"
#include "Network/NetZ/DSStartTime.h"
#include "Network/NetZ/DOMessageOwner.h"
#include "Network/NetZ/AvalancheDDF.h"
class DOWorld;
BEGIN_NAMESPACE_QUAZAL;

class DOCLASS(DOWorld): public DOMessageOwner {
public:
	_DO_DeclareGeneralMethods(DOWorld);

	_DSDECL_DSWorldExtents	d_extents;
	_DSDECL_DSStartTime	d_start;
	_PR_userdo_pudecl();
	_PR_globaldo_pudecl();
protected:
	_PR_userdo_prdecl();
	_PR_globaldo_prdecl();
protected:


private:
};
END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DOCLASS(DOWorld);
BEGIN_NAMESPACE_QUAZAL;

class _DOC_DOWorld: public DOClassTemplate<DOCLASS(DOWorld), _DOC_DOMessageOwner> {
public:
	_DOC_DeclareGeneralMethods(DOWorld)
};
END_NAMESPACE_QUAZAL;

#endif // _DOWorldDDL_H_
