// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSActorInteraction.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSActorInteraction);
_PR_upon_request_filter_impl(DSActorInteraction);

	qBool DATASET(DSActorInteraction)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_category,d_category);
		_DS_FormatMatchingVariableValue(Td_involvement,d_involvement);
		_DS_FormatMatchingVariableValue(Td_negativeExclude,d_negativeExclude);
		_DS_FormatMatchingVariableValue(Td_negativeInclude,d_negativeInclude);
		_DS_FormatMatchingVariableValue(Td_positiveExclude,d_positiveExclude);
		_DS_FormatMatchingVariableValue(Td_positiveInclude,d_positiveInclude);
		return false;
	}

	void DATASET(DSActorInteraction)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_category,d_category);
		_MSG_ADD_VARIABLE(Td_involvement,d_involvement);
		_MSG_ADD_VARIABLE(Td_negativeExclude,d_negativeExclude);
		_MSG_ADD_VARIABLE(Td_negativeInclude,d_negativeInclude);
		_MSG_ADD_VARIABLE(Td_positiveExclude,d_positiveExclude);
		_MSG_ADD_VARIABLE(Td_positiveInclude,d_positiveInclude);
	}

END_NAMESPACE_QUAZAL;
