// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSActorMigrate.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSActorMigrate);
_PR_upon_request_filter_impl(DSActorMigrate);

	qBool DATASET(DSActorMigrate)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_persistent,d_persistent);
		return false;
	}

	void DATASET(DSActorMigrate)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_persistent,d_persistent);
	}

END_NAMESPACE_QUAZAL;
