// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSActorInteractionDDL_H_
#define _DSActorInteractionDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSActorInteraction): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSActorInteraction);
	DATASET(DSActorInteraction)( const DATASET(DSActorInteraction) &oOther ) :
		d_category(oOther.d_category), 
		d_involvement(oOther.d_involvement), 
		d_negativeExclude(oOther.d_negativeExclude), 
		d_negativeInclude(oOther.d_negativeInclude), 
		d_positiveExclude(oOther.d_positiveExclude), 
		d_positiveInclude(oOther.d_positiveInclude)
	{
	}

	_DS_ASSIGN_OPERATOR(DSActorInteraction){
		_DS_COPYDATASET_VAR(d_category);
		_DS_COPYDATASET_VAR(d_involvement);
		_DS_COPYDATASET_VAR(d_negativeExclude);
		_DS_COPYDATASET_VAR(d_negativeInclude);
		_DS_COPYDATASET_VAR(d_positiveExclude);
		_DS_COPYDATASET_VAR(d_positiveInclude);
	}

	_DS_EQUAL_OPERATOR(DSActorInteraction){
		_DS_EQUAL_VAR(d_category);
		_DS_EQUAL_VAR(d_involvement);
		_DS_EQUAL_VAR(d_negativeExclude);
		_DS_EQUAL_VAR(d_negativeInclude);
		_DS_EQUAL_VAR(d_positiveExclude);
		_DS_EQUAL_VAR(d_positiveInclude);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSActorInteraction)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_category,d_category);
		_MSG_EXTRACT_VARIABLE(Td_involvement,d_involvement);
		_MSG_EXTRACT_VARIABLE(Td_negativeExclude,d_negativeExclude);
		_MSG_EXTRACT_VARIABLE(Td_negativeInclude,d_negativeInclude);
		_MSG_EXTRACT_VARIABLE(Td_positiveExclude,d_positiveExclude);
		_MSG_EXTRACT_VARIABLE(Td_positiveInclude,d_positiveInclude);
	}

	DDLTYPE(uint32)::CPPType d_category;
	DDLTYPE(uint32)::CPPType d_involvement;
	DDLTYPE(uint32)::CPPType d_negativeExclude;
	DDLTYPE(uint32)::CPPType d_negativeInclude;
	DDLTYPE(uint32)::CPPType d_positiveExclude;
	DDLTYPE(uint32)::CPPType d_positiveInclude;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(uint32) Td_category;
	typedef DDLTYPE(uint32) Td_involvement;
	typedef DDLTYPE(uint32) Td_negativeExclude;
	typedef DDLTYPE(uint32) Td_negativeInclude;
	typedef DDLTYPE(uint32) Td_positiveExclude;
	typedef DDLTYPE(uint32) Td_positiveInclude;
};

#define _DSDECL_DSActorInteraction DSActorInteraction

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSActorInteraction);


#endif // _DSActorInteractionDDL_H_
