// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSActorProps.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSActorProps);

	qBool DATASET(DSActorProps)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_parm,d_parm);
		return false;
	}

	void DATASET(DSActorProps)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_parm,d_parm);
	}

END_NAMESPACE_QUAZAL;
