// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSActorMigrateDDL_H_
#define _DSActorMigrateDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSActorMigrate): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSActorMigrate);
	DATASET(DSActorMigrate)( const DATASET(DSActorMigrate) &oOther ) :
		d_persistent(oOther.d_persistent)
	{
	}

	_DS_ASSIGN_OPERATOR(DSActorMigrate){
		_DS_COPYDATASET_VAR(d_persistent);
	}

	_DS_EQUAL_OPERATOR(DSActorMigrate){
		_DS_EQUAL_VAR(d_persistent);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSActorMigrate)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_persistent,d_persistent);
	}

	DDLTYPE(bool)::CPPType d_persistent;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(bool) Td_persistent;
};

#define _DSDECL_DSActorMigrate DSActorMigrate

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSActorMigrate);


#endif // _DSActorMigrateDDL_H_
