// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSBufferDDL_H_
#define _DSBufferDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSBuffer): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSBuffer);
	DATASET(DSBuffer)( const DATASET(DSBuffer) &oOther ) :
		d_buffer(oOther.d_buffer)
	{
	}

	_DS_ASSIGN_OPERATOR(DSBuffer){
		_DS_COPYDATASET_VAR(d_buffer);
	}

	_DS_EQUAL_OPERATOR(DSBuffer){
		_DS_EQUAL_VAR(d_buffer);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSBuffer)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_buffer,d_buffer);
	}

	DDLTYPE(buffer)::CPPType d_buffer;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(buffer) Td_buffer;
};

#define _DSDECL_DSBuffer DSBuffer

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSBuffer);


#endif // _DSBufferDDL_H_
