// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSBuffer.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSBuffer);
_PR_upon_request_filter_impl(DSBuffer);

	qBool DATASET(DSBuffer)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_buffer,d_buffer);
		return false;
	}

	void DATASET(DSBuffer)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_buffer,d_buffer);
	}

END_NAMESPACE_QUAZAL;
