// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSGroundFollower.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSGroundFollower);
_PR_unreliable_impl(DSGroundFollower);

	qBool DATASET(DSGroundFollower)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_flags,d_flags);
		_DS_FormatMatchingVariableValue(Td_heading,d_heading);
		_DS_FormatMatchingVariableValue(Td_headingRate,d_headingRate);
		_DS_FormatMatchingVariableValue(Td_posX,d_posX);
		_DS_FormatMatchingVariableValue(Td_posY,d_posY);
		_DS_FormatMatchingVariableValue(Td_posZ,d_posZ);
		_DS_FormatMatchingVariableValue(Td_velX,d_velX);
		_DS_FormatMatchingVariableValue(Td_velY,d_velY);
		_DS_FormatMatchingVariableValue(Td_velZ,d_velZ);
		return false;
	}

	void DATASET(DSGroundFollower)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_flags,d_flags);
		_MSG_ADD_VARIABLE(Td_heading,d_heading);
		_MSG_ADD_VARIABLE(Td_headingRate,d_headingRate);
		_MSG_ADD_VARIABLE(Td_posX,d_posX);
		_MSG_ADD_VARIABLE(Td_posY,d_posY);
		_MSG_ADD_VARIABLE(Td_posZ,d_posZ);
		_MSG_ADD_VARIABLE(Td_velX,d_velX);
		_MSG_ADD_VARIABLE(Td_velY,d_velY);
		_MSG_ADD_VARIABLE(Td_velZ,d_velZ);
	}

END_NAMESPACE_QUAZAL;
