// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSHostStateDDL_H_
#define _DSHostStateDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSHostState): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSHostState);
	DATASET(DSHostState)( const DATASET(DSHostState) &oOther ) :
		d_acceptImmigration(oOther.d_acceptImmigration)
	{
	}

	_DS_ASSIGN_OPERATOR(DSHostState){
		_DS_COPYDATASET_VAR(d_acceptImmigration);
	}

	_DS_EQUAL_OPERATOR(DSHostState){
		_DS_EQUAL_VAR(d_acceptImmigration);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSHostState)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_acceptImmigration,d_acceptImmigration);
	}

	DDLTYPE(bool)::CPPType d_acceptImmigration;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(bool) Td_acceptImmigration;
};

#define _DSDECL_DSHostState DSHostState

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSHostState);


#endif // _DSHostStateDDL_H_
