// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSSessionLock.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSSessionLock);
_PR_upon_request_filter_impl(DSSessionLock);

	qBool DATASET(DSSessionLock)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_grantee,d_grantee);
		_DS_FormatMatchingVariableValue(Td_ids,d_ids);
		return false;
	}

	void DATASET(DSSessionLock)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_grantee,d_grantee);
		_MSG_ADD_VARIABLE(Td_ids,d_ids);
	}

END_NAMESPACE_QUAZAL;
