// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSSixDOFDDL_H_
#define _DSSixDOFDDL_H_

#include <NetZ.h>
#include "Network/NetZ/AvalancheProperties.h"
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSSixDOF): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSSixDOF);
	DATASET(DSSixDOF)( const DATASET(DSSixDOF) &oOther ) :
		d_flags(oOther.d_flags), 
		d_omegaX(oOther.d_omegaX), 
		d_omegaY(oOther.d_omegaY), 
		d_omegaZ(oOther.d_omegaZ), 
		d_orientW(oOther.d_orientW), 
		d_orientX(oOther.d_orientX), 
		d_orientY(oOther.d_orientY), 
		d_orientZ(oOther.d_orientZ), 
		d_posX(oOther.d_posX), 
		d_posY(oOther.d_posY), 
		d_posZ(oOther.d_posZ), 
		d_velX(oOther.d_velX), 
		d_velY(oOther.d_velY), 
		d_velZ(oOther.d_velZ)
	{
	}

	_DS_ASSIGN_OPERATOR(DSSixDOF){
		_DS_COPYDATASET_VAR(d_flags);
		_DS_COPYDATASET_VAR(d_omegaX);
		_DS_COPYDATASET_VAR(d_omegaY);
		_DS_COPYDATASET_VAR(d_omegaZ);
		_DS_COPYDATASET_VAR(d_orientW);
		_DS_COPYDATASET_VAR(d_orientX);
		_DS_COPYDATASET_VAR(d_orientY);
		_DS_COPYDATASET_VAR(d_orientZ);
		_DS_COPYDATASET_VAR(d_posX);
		_DS_COPYDATASET_VAR(d_posY);
		_DS_COPYDATASET_VAR(d_posZ);
		_DS_COPYDATASET_VAR(d_velX);
		_DS_COPYDATASET_VAR(d_velY);
		_DS_COPYDATASET_VAR(d_velZ);
	}

	_DS_EQUAL_OPERATOR(DSSixDOF){
		_DS_EQUAL_VAR(d_flags);
		_DS_EQUAL_VAR(d_omegaX);
		_DS_EQUAL_VAR(d_omegaY);
		_DS_EQUAL_VAR(d_omegaZ);
		_DS_EQUAL_VAR(d_orientW);
		_DS_EQUAL_VAR(d_orientX);
		_DS_EQUAL_VAR(d_orientY);
		_DS_EQUAL_VAR(d_orientZ);
		_DS_EQUAL_VAR(d_posX);
		_DS_EQUAL_VAR(d_posY);
		_DS_EQUAL_VAR(d_posZ);
		_DS_EQUAL_VAR(d_velX);
		_DS_EQUAL_VAR(d_velY);
		_DS_EQUAL_VAR(d_velZ);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSSixDOF)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_flags,d_flags);
		_MSG_EXTRACT_VARIABLE(Td_omegaX,d_omegaX);
		_MSG_EXTRACT_VARIABLE(Td_omegaY,d_omegaY);
		_MSG_EXTRACT_VARIABLE(Td_omegaZ,d_omegaZ);
		_MSG_EXTRACT_VARIABLE(Td_orientW,d_orientW);
		_MSG_EXTRACT_VARIABLE(Td_orientX,d_orientX);
		_MSG_EXTRACT_VARIABLE(Td_orientY,d_orientY);
		_MSG_EXTRACT_VARIABLE(Td_orientZ,d_orientZ);
		_MSG_EXTRACT_VARIABLE(Td_posX,d_posX);
		_MSG_EXTRACT_VARIABLE(Td_posY,d_posY);
		_MSG_EXTRACT_VARIABLE(Td_posZ,d_posZ);
		_MSG_EXTRACT_VARIABLE(Td_velX,d_velX);
		_MSG_EXTRACT_VARIABLE(Td_velY,d_velY);
		_MSG_EXTRACT_VARIABLE(Td_velZ,d_velZ);
	}

	DDLTYPE(byte)::CPPType d_flags;
	DDLTYPE(int16)::CPPType d_omegaX;
	DDLTYPE(int16)::CPPType d_omegaY;
	DDLTYPE(int16)::CPPType d_omegaZ;
	DDLTYPE(int16)::CPPType d_orientW;
	DDLTYPE(int16)::CPPType d_orientX;
	DDLTYPE(int16)::CPPType d_orientY;
	DDLTYPE(int16)::CPPType d_orientZ;
	DDLTYPE(int16)::CPPType d_posX;
	DDLTYPE(int16)::CPPType d_posY;
	DDLTYPE(int16)::CPPType d_posZ;
	DDLTYPE(int16)::CPPType d_velX;
	DDLTYPE(int16)::CPPType d_velY;
	DDLTYPE(int16)::CPPType d_velZ;
	_PR_unreliable_pudecl();

protected:
	_PR_unreliable_prdecl();
private:
	typedef DDLTYPE(byte) Td_flags;
	typedef DDLTYPE(int16) Td_omegaX;
	typedef DDLTYPE(int16) Td_omegaY;
	typedef DDLTYPE(int16) Td_omegaZ;
	typedef DDLTYPE(int16) Td_orientW;
	typedef DDLTYPE(int16) Td_orientX;
	typedef DDLTYPE(int16) Td_orientY;
	typedef DDLTYPE(int16) Td_orientZ;
	typedef DDLTYPE(int16) Td_posX;
	typedef DDLTYPE(int16) Td_posY;
	typedef DDLTYPE(int16) Td_posZ;
	typedef DDLTYPE(int16) Td_velX;
	typedef DDLTYPE(int16) Td_velY;
	typedef DDLTYPE(int16) Td_velZ;
};

#define _DSDECL_DSSixDOF DeadReckoningDSDecl< DSSixDOF, _PR_DRSixDOF_model(DSSixDOF), _PR_DRSixDOF_modelpolicy(_PR_DRSixDOF_model(DSSixDOF)) >

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSSixDOF);


#endif // _DSSixDOFDDL_H_
