// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSStartTimeDDL_H_
#define _DSStartTimeDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSStartTime): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSStartTime);
	DATASET(DSStartTime)( const DATASET(DSStartTime) &oOther ) :
		d_time(oOther.d_time)
	{
	}

	_DS_ASSIGN_OPERATOR(DSStartTime){
		_DS_COPYDATASET_VAR(d_time);
	}

	_DS_EQUAL_OPERATOR(DSStartTime){
		_DS_EQUAL_VAR(d_time);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSStartTime)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_time,d_time);
	}

	DDLTYPE(uint64)::CPPType d_time;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(uint64) Td_time;
};

#define _DSDECL_DSStartTime DSStartTime

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSStartTime);


#endif // _DSStartTimeDDL_H_
