// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSStartTime.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSStartTime);
_PR_upon_request_filter_impl(DSStartTime);

	qBool DATASET(DSStartTime)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_time,d_time);
		return false;
	}

	void DATASET(DSStartTime)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_time,d_time);
	}

END_NAMESPACE_QUAZAL;
