// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#include "Network/NetworkPCH.h"
#include "Network/NetZ/DSTalkerProps.h"
BEGIN_NAMESPACE_QUAZAL;
	_DS_IMPLEMENT(DSTalkerProps);
_PR_upon_request_filter_impl(DSTalkerProps);

	qBool DATASET(DSTalkerProps)::FormatVariableValue(Variable* pVariable, NS_QUAZAL String *pstrResult) const {
		_DS_FormatMatchingVariableValue(Td_environ,d_environ);
		_DS_FormatMatchingVariableValue(Td_headset,d_headset);
		_DS_FormatMatchingVariableValue(Td_id,d_id);
		_DS_FormatMatchingVariableValue(Td_pitchOffset,d_pitchOffset);
		_DS_FormatMatchingVariableValue(Td_pitchWarp,d_pitchWarp);
		_DS_FormatMatchingVariableValue(Td_robot,d_robot);
		_DS_FormatMatchingVariableValue(Td_spectrumLedge,d_spectrumLedge);
		_DS_FormatMatchingVariableValue(Td_spectrumOffset,d_spectrumOffset);
		_DS_FormatMatchingVariableValue(Td_spectrumWarp,d_spectrumWarp);
		_DS_FormatMatchingVariableValue(Td_userFlags,d_userFlags);
		_DS_FormatMatchingVariableValue(Td_voiceToSpeakers,d_voiceToSpeakers);
		_DS_FormatMatchingVariableValue(Td_whisper,d_whisper);
		return false;
	}

	void DATASET(DSTalkerProps)::AddSourceTo(Message *pMsg, Time tTimestamp, qBool bDiscovery) {
		DUMMY_PARAM(tTimestamp);DUMMY_PARAM(bDiscovery);
		_MSG_ADD_VARIABLE(Td_environ,d_environ);
		_MSG_ADD_VARIABLE(Td_headset,d_headset);
		_MSG_ADD_VARIABLE(Td_id,d_id);
		_MSG_ADD_VARIABLE(Td_pitchOffset,d_pitchOffset);
		_MSG_ADD_VARIABLE(Td_pitchWarp,d_pitchWarp);
		_MSG_ADD_VARIABLE(Td_robot,d_robot);
		_MSG_ADD_VARIABLE(Td_spectrumLedge,d_spectrumLedge);
		_MSG_ADD_VARIABLE(Td_spectrumOffset,d_spectrumOffset);
		_MSG_ADD_VARIABLE(Td_spectrumWarp,d_spectrumWarp);
		_MSG_ADD_VARIABLE(Td_userFlags,d_userFlags);
		_MSG_ADD_VARIABLE(Td_voiceToSpeakers,d_voiceToSpeakers);
		_MSG_ADD_VARIABLE(Td_whisper,d_whisper);
	}

END_NAMESPACE_QUAZAL;
