// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED.
// File generated by Quazal DDL Compiler, Version 4.1 [SP2] (Build 1224.83)
// Copyright (C) 1998-2004, Quazal Technologies Inc.

#ifndef _DSWorldExtentsDDL_H_
#define _DSWorldExtentsDDL_H_

#include <NetZ.h>
BEGIN_NAMESPACE_QUAZAL;
class DATASET(DSWorldExtents): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS(DSWorldExtents);
	DATASET(DSWorldExtents)( const DATASET(DSWorldExtents) &oOther ) :
		d_centerX(oOther.d_centerX), 
		d_centerY(oOther.d_centerY), 
		d_centerZ(oOther.d_centerZ), 
		d_extentX(oOther.d_extentX), 
		d_extentY(oOther.d_extentY), 
		d_extentZ(oOther.d_extentZ), 
		d_set(oOther.d_set)
	{
	}

	_DS_ASSIGN_OPERATOR(DSWorldExtents){
		_DS_COPYDATASET_VAR(d_centerX);
		_DS_COPYDATASET_VAR(d_centerY);
		_DS_COPYDATASET_VAR(d_centerZ);
		_DS_COPYDATASET_VAR(d_extentX);
		_DS_COPYDATASET_VAR(d_extentY);
		_DS_COPYDATASET_VAR(d_extentZ);
		_DS_COPYDATASET_VAR(d_set);
	}

	_DS_EQUAL_OPERATOR(DSWorldExtents){
		_DS_EQUAL_VAR(d_centerX);
		_DS_EQUAL_VAR(d_centerY);
		_DS_EQUAL_VAR(d_centerZ);
		_DS_EQUAL_VAR(d_extentX);
		_DS_EQUAL_VAR(d_extentY);
		_DS_EQUAL_VAR(d_extentZ);
		_DS_EQUAL_VAR(d_set);
		return true;
	}

	_DS_TMPL_EQUAL_OPERATOR(DSWorldExtents)
	void ExtractFrom(Message* pMsg) {
		_MSG_EXTRACT_VARIABLE(Td_centerX,d_centerX);
		_MSG_EXTRACT_VARIABLE(Td_centerY,d_centerY);
		_MSG_EXTRACT_VARIABLE(Td_centerZ,d_centerZ);
		_MSG_EXTRACT_VARIABLE(Td_extentX,d_extentX);
		_MSG_EXTRACT_VARIABLE(Td_extentY,d_extentY);
		_MSG_EXTRACT_VARIABLE(Td_extentZ,d_extentZ);
		_MSG_EXTRACT_VARIABLE(Td_set,d_set);
	}

	DDLTYPE(float)::CPPType d_centerX;
	DDLTYPE(float)::CPPType d_centerY;
	DDLTYPE(float)::CPPType d_centerZ;
	DDLTYPE(float)::CPPType d_extentX;
	DDLTYPE(float)::CPPType d_extentY;
	DDLTYPE(float)::CPPType d_extentZ;
	DDLTYPE(bool)::CPPType d_set;
	_PR_upon_request_filter_pudecl();

protected:
	_PR_upon_request_filter_prdecl();
private:
	typedef DDLTYPE(float) Td_centerX;
	typedef DDLTYPE(float) Td_centerY;
	typedef DDLTYPE(float) Td_centerZ;
	typedef DDLTYPE(float) Td_extentX;
	typedef DDLTYPE(float) Td_extentY;
	typedef DDLTYPE(float) Td_extentZ;
	typedef DDLTYPE(bool) Td_set;
};

#define _DSDECL_DSWorldExtents DSWorldExtents

END_NAMESPACE_QUAZAL;
// For convenience, this declaration is directly available outside the Quazal namespace
using NS_QUAZAL DATASET(DSWorldExtents);


#endif // _DSWorldExtentsDDL_H_
